INSERT INTO feats (`type`, `name`, `source`, `prerequisites`, `Benefit`) VALUES
('Epic','Arcane Mastery','PHB','Wizard','Regain daily spell by spending action point'),
('Epic','Artful Provocation','MP','Charisma 17, rogue, Artful Dodger','Missed opportunity attack grants combat advantage against attacker'),
('Epic','Axe Mastery','PHB','Str 21, Con 17','Critical hit with axe melee attack roll of 19 or 20'),
('Epic','Blind-Fight','PHB','Wis 13 or trained in Perception','Adjacent creatures aren’t concealed or invisible to you'),
('Epic','Bludgeon Mastery','PHB','Str 19, Con 19','Critical hit with bludgeoning melee attack roll of 19 or 20'),
('Epic','Brutal Advantage','MP','Charisma 17, rogue, Brutal Scoundrel','Add Strength modifier to damage when you have combat advantage'),
('Epic','Darkfire Warrior','MP','Drow, any martial class','Regain use of darkfire after reducing target to 0 hp'),
('Epic','Dragon Warrior','MP','Constitution 17, dragonborn, any martial class','Regain dragon breath when first bloodied'),
('Epic','Elemental Warrior','MP','Genasi, any martial class','Regain use of racial power after scoring critical hit'),
('Epic','Epic Recovery','MP','Constitution 19, any martial class','Use second wind twice per encounter'),
('Epic','Epic Resurgence','PHB','-','Regain encounter attack power on first critical hit'),
('Epic','Feywild Warrior','MP','Dexterity 17, eladrin, any martial class','Teleport yourself and your target after using daily power'),
('Epic','Flail Mastery','PHB','Str 19, Dex 19','Critical hit with flail melee attack roll of 19 or 20'),
('Epic','Flanking Maneuver','PHB','Dex 17, trained in Acrobatics','Move diagonally past walls and through enemies’ spaces'),
('Epic','Font of Radiance','PHB','-','Target illuminated with critical hit, takes radiant damage'),
('Epic','Fortune’s Warrior','MP','Dexterity 17, halfling, any martial class','Gain combat advantage after using second chance'),
('Epic','Hawkeye Warrior','MP','Wisdom 17, elf, any martial class','+1 to attack rolls after using elven accuracy'),
('Epic','Heavy Blade Mastery','PHB','Str 21, Dex 17','Critical hit with heavy blade melee attack roll of 19 or 20'),
('Epic','Infernal Warrior','MP','Charisma 17, tiefling, any martial class','Retaliate against a critical hit with infernal wrath'),
('Epic','Invigorating Exploit','MP','any martial class','Martial attack power becomes invigorating'),
('Epic','Irresistible Flame','PHB','-','Decrease target’s resist fire by 20'),
('Epic','Lasting Advantage','MP','rogue','Target grants combat advantage to you after a critical hit'),
('Epic','Light Blade Mastery','PHB','Str 17, Dex 21','Critical hit with light blade melee attack roll of 19 or 20'),
('Epic','Martial Mastery','MP','any martial class','Regain encounter power when spending action point'),
('Epic','Martial Resolve','MP','Wisdom 15, any martial class,Endurance trained','Make saving throws against certain conditions at both start and end of turn'),
('Epic','One with Shadow','MP','rogue','Move through enemies’ spaces while hidden'),
('Epic','Pick Mastery','PHB','Str 21, Con 17','Critical hit with pick melee attack roll of 19 or 20'),
('Epic','Rattling Exploit','MP','any martial class','Martial attack power becomes rattling'),
('Epic','Ruthless Terror','MP','Strength 17, rogue, Ruthless Ruffian, Intimidate trained','Rattling attacks apply −1 penalty on a miss'),
('Epic','Spear Mastery','PHB','Str 19, Dex 19','Critical hit with spear melee attack roll of 19 or 20'),
('Epic','Spell Accuracy','PHB','Wizard','Omit squares from any area or close wizard power'),
('Epic','Stoneheart Warrior','MP','Constitution 17, dwarf, any martial class','Use second wind as free action'),
('Epic','Superior Initiative','PHB3','','+8 to initiative checks'),
('Epic','Timely Revival','MP','human, any martial class','Make death saving throws at the start of your turn'),
('Epic','Triumphant Attack','PHB','-','Target at −2 to attacks and defenses after a meleecritical hit'),
('Epic','Two-Weapon Flurry','PHB','Dex 19, Two-Weapon Fighting','Make opportunity attack with off-hand melee weapon'),
('Epic','Unfettered Stride','PHB','Trained in Acrobatics','Ignore the effect of difficult terrain on your movement'),
('Epic','Whirlwind Sneak Attack','MP','rogue, Sneak Attack','Deal Sneak Attack damage to all targets of a rogue encounter attack power')