INSERT INTO feats (`id`, `type`, `name`, `source`, `prerequisites`, `Benefit`) VALUES
('Accursed Coordination','AP','Warlock, Warlock`s Curse','Place your curse on a creature already cursed by another'),
('Action Rush','MP2','Human, rogue or Ranger','Shift 2 squares after spending action point'),
('Action Surge','PHB','Human','+3 to attack rolls when you spend an action point'),
('Advantage of Cunning','PHB2','Bard, Virtue of Cunning','Slide enemy into ally`s vacated space'),
('Agile Hunter','PHB','Dex 15, Ranger, Hunter`s Quarry','Shift as a free action after scoring a critical hit'),
('Agile Running Attack','MP2','Ranger, Running Attack','Ignore difficult terrain when moving as part of an attack'),
('Agile Stand','MP2','Ranger, Rogue','Shift when standing up'),
('Aggressive Advantage','Essentials','-','Combat advantage against enemies during your first turn in an encounter'),
('Aggressive Assault','MP','Rogue, Brutal Scoundrel, First Strike','Slide targets that have not yet acted 1 square'),
('Agile Form','PrP','Druid, Wild shape','Shift 1 when you use Wild shape'),
('Agile Stand','MP2','Rogue','Shift when standing up'),
('Alchemist','AV, EPG','-','Create alchemical items'),
('Alertness','PHB,Essentials','-','No combat advantage when surprised, +2 toPerception'),
('Alhahn`s Mindful Relocation','PHB3','Githzerai, Shifting Fortunes','Shift up to speed as a free action when usingsecond wind'),
('Ambush Tactics','MP2','Any martial class','1d6 extra damage against enemy that has not yet acted'),
('Anger Unleashed','PHB2','Half-orc','+2 attack for 1 round after becoming bloodied'),
('Animal Empathy','PrP','Any Primal class, Trained inNature','+2 to Nature checks, and substitute Nature for Insight when dealing with beasts'),
('Ankle Cutter','MP','Halfling, Rogue, Sneak Attack','Cause Large or larger Sneak Attack target to beslowed'),
('Arcane Familiar','AP,HotEC,HotFW','Any Arcane class','You gain a familiar'),
('Arcane Fire','AP','Int 13, Any arcane class','Target hit with fire power gains vulnerability to cold'),
('Arcane Fury','AP','Half-orc, Any arcane class','Deal extra furious assault damage to multiple targets'),
('Arcane Implement Proficiency','AP','Any arcane class','Use an implement group with which an arcane class is proficient, with arcane powers'),
('Arcane Porter','HotFW','Arcane Familiar','Your familiar can carry a 5-pound object'),
('Arcane Reserves','AP','Human, Any arcane class','+2 to damage with at-will powers when encounter powers are expended'),
('Arcane Spellfury','PHB2','Sorcerer','+1 to attack rolls after hitting with sorcerer at-will attack'),
('Archer Captain','MP2','Warlord, Archer Warlord','You and allies ignore long range penalty'),
('Archery Mastery','D400','Leveled ranger at-will attack power','Swap a leveled ranger at-will attack power foraimed shot, clever shot, or rapid shot'),
('Armor Finesse','Essentials','-','Ignore the check penalty for wearing armor'),
('Armor of Bahamut','PHB','Channel Divinity, must worshipBahamut','Use Channel Divinity to invoke Armor of Bahamut'),
('Armour of Burning Wrath','DP','Invoker, Covenant of Wrath','Armour of wrath gains fire keyword, and target takes -1 to saving throws'),
('Armour of Vengeance','DP','Avenger, Censure of Retribution, Oath of enmity','+1 to defenses against creatures other than yourOath of enmity target'),
('Armor Proficiency: Chainmail','PHB','Str 13, Con 13, training withleather armor or hide armor','Training with chainmail armor'),
('Armor Proficiency: Hide','PHB','Str 13, Con 13, training withleather armor','Training with hide armor'),
('Armor Proficiency: Leather','PHB','-','Training with Leather Armor'),
('Armor Proficiency: Plate','PHB','Str 15, Con 15, training withscale armor','Training with plate armor'),
('Armor Proficiency: Scale','PHB','Str 13, Con 13, training withchainmail','Training with scale armor'),
('Armored Endurance Training','MP2','Any martial class','No armor penalty to Strength and Constitution skills'),
('Armoured Warlord','MP2','Warlord, Battlefront Leader','Gain proficiency with scale armour and one extra healing surge'),
('Armored Swiftness Training','MP2','Any martial class','No armor penalty to Dexterity skills'),
('Astral Enmity','DP','Deva, Avenger, Oath of enmity','Bonus from Memory of a thousand lifetimes also applies to damage rolls against your Oath of enmitytarget'),
('Astral Fire','PHB','Dex 13, Cha 13','+1 damage with fire or radiant power'),
('Astral Preservation','DP','Deva, Invoker, Covenant of Preservation','When you use preserver`s rebuke, nearby allies gain +1 against attacks by bloodied creatures'),
('Audacious Lineage','PrP','-','+2 to Thievery checks; increase by 1 for each ally with feat'),
('Auspicious Lineage','PHB2','Deva','Roll d8 instead of d6 for memory of a thousand lifetimes'),
('Autohypnosis','PsP','Any Psionic class, trained inArcana','Gain 1 healing surge; substitute Arcana for Endurance'),
('Avandra’s Rescue','PHB','Channel Divinity class feature , must worship Avandra','Use Channel Divinity to invoke Avandra’s Rescue'),
('Avenging Allure','DP','Avenger, Censure of Unity','Pull target 2 extra squares when you use Bond of censure'),
('Avenging Opportunist','DP','Human, Avenger, Oath of enmity','Gain extra move action when you reduce your Oath of enmity target to 0 hit points'),
('Axe Expertise','Essentials','-','+1 to attack rolls with an axe, when rolling damage for an attack with an axe, you can reroll one damage die that results in a 1'),
('Backstabber','PHB','Rogue, Sneak Attack class feature','Sneak Attack dice increase to d8s'),
('Baleful Malediction','DP','Invoker, Covenant of Malediction','Enemies you hit with encounter or daily powers take -2 to attacks against you'),
('Bardic Knowledge','PHB2','Bard','+2 bonus to several skill checks'),
('Barreling Charge','MP2','Any martial class','Charge to adjacent square with reach weapon'),
('Battle Hardened','PHB3','-','+5 to saving throws against fear, +2 to initiative checks'),
('Battle Caster Defense','PHB3','-','+4 to AC vs. opportunity attacks provoked by ranged or area powers'),
('Battle Healer','DP','Cleric, Healing word (cleric)','Regain Str hit points when you use Healing word (cleric)'),
('Battering Shield','PHB3','Proficiency with heavy shields','Push or slide target 1 additional square when using shield'),
('Battlewise','Essentials','-','Use Wis rather than Dex to determine initiative'),
('Beast Guidance','MP','Ranger, Beast Mastery','Beast gains +2 to your trained skills'),
('Beast Protector','MP','Ranger, Beast Mastery','Attack against beast provokes opportunity attack from you'),
('Beast Training','MP','Ranger, Beast Mastery','Beast gains training in a skill'),
('Beastwalker Circle','HotFW','Druid, Summon Natural Ally','Gain wild shape, exchange summon natural ally for druid daily power'),
('Befuddling Thoughts','PsP','Changeling, Psion, Changeling Trick, Send Thoughts,Telepathy Focus','Changeling trick becomes ranged 20 with send thoughts'),
('Beguiling Enchantment','PHB3','-','Enemy -2 to attacks after you hit it with charm power'),
('Beguiling Torment','PsP','Psionic Augmentation','When you daze or stun, augment to slide enemy'),
('Berserk Vitaity','HotFW','Barbarian, Berserker Fury','Gain temporary hp when you enter berserker fury'),
('Blade Opportunist','PHB','Str 13, Dex 13','+2 to opportunity attacks with heavy blade or light blade'),
('Blessed Scoundrel','DP','Halfling, Any Divine class','Spend healing surge with second chance'),
('Blessed Shifter','DP','Shifter, Paladin','Gain more damage with melee attacks when you use shifting'),
('Blessing of Avandra','DP','Halfling, Cleric','If enemy misses due to Second chance, ally can spend healing surge'),
('Blessing of Corellon','DP','Elf, Cleric','If you hit with Elven accuracy, an ally can spend healing surge'),
('Blindfighting Sentinel','Essentials','-','Invisible enemies don`t have combat advantage, blindness does not penalize Perception, +2 Perception'),
('Blindfighting Warrior','Essentials','-','Melee attacks ignore partial and total concealment'),
('Blood Quarry','MP2','Tiefling, Ranger, Hunter`s Quarry','+2 to attack when using Bloodhunt against quarry'),
('Bloodied Concentration','PsP','Psion','+1 to attacks with augmented at-will powers when bloodied'),
('Bloodied Elusion','PHB3','Seeker, Bloodbond','Shift 1 square when bloodied by any attack'),
('Bloodied Enmity','PsP','Ardent, Mantle of Impulsiveness','When first bloodied, melee attacks deal 1d6 extra damage'),
('Bloodied Ferocity','PHB3','Minotaur','Make free melee basic attack when first bloodied'),
('Bloodied Invigoration','MP','Con 13, Dragonborn, Fighter','Invigorating powers grant +2 temporary hp when bloodied'),
('Bloodied Spear','PrP','-','+1 to attack and damage with opportunity attacks, increase by 1 for each ally with feat'),
('Bloody Triumph','PrP','Barbarian','Gain bonus to next damage roll against enemy you bloody'),
('Bludgeon Expertise','Essentials','-','+1 to attack rolls with a hammer  or mace, +1 to number of squares a target is pushed with an attack using a hammer or mace'),
('Blurred Speed','PsP','Battlemind, Blurred Step','Shift 2 with Blurred step'),
('Blurring Claws','PHB2','Razorclaw shifter','+2 damage with combat advantage duringrazorclaw shifting'),
('Bold Command','MP','Halfling, Warlord, Bravura Presence','Allies gain +1 to attack rolls against enemy that misses you'),
('Bolstering Inspiration','MP','Dwarf, Warlord','Saving throw or additional hp for Inspiring wordtarget'),
('Bolstering Mantle','PHB3','Ardent, Ardent Mantle','Spend healing surge, ally gains temporary hp or saving throw'),
('Bolstering Spike','PsP','Battlemind, Mind spike','Gain temporary hit points with mind spike'),
('Bonded Familiar','AP','Arcane Familiar','Communicate telepathically with your familiar'),
('Born of Shadow','HoS','-','Shadow origin and +1 to saving throws in dim light and darkness'),
('Born of the Elements','HotEC','Elemental origin or training inArcana','+2 to Endurance and Intimidate; gain Primordial'),
('Bow Expertise','Essentials','-','+1 to attack rolls with a bow , +1 damage with attack using a bow against a single creature with no creature adjacent to it'),
('Bracing Breath','MP','Con 13, Dragonborn, Fighter','Dragon breath gives +1 to attack with invigorating powers'),
('Bravura Spirit','MP','Dragonborn, Warlord, Bravura Presence','Bloodied ally gains additional bonus from Bravura Presence'),
('Brawler Guard','MP2','Fighter, Brawler Style','+1 Shield bonus to AC and Reflex when one hand is free'),
('Breath of Life','DP','Dragonborn, Cleric','Your Dragon breath gives temporary hp to allies'),
('Breath-Resistant Beast','MP','Dragonborn, Ranger, Beast Mastery','Beast gains resistance to your dragon breath`s damage type'),
('Brilliant Darkfire','DP','Drow, Any Divine class','Targets of Darkfire gain vulnerable Cha radiant'),
('Brimming Wrath','PsP','Half-orc, Battlemind, Furious Assault','Marked enemies take damage when you usefurious assault'),
('Brutal Accuracy','MP','Elf, Ranger, Hunter`s Quarry','Hit with Elven accuracy reroll gains extra damage'),
('Brutal Brawler','MP2','Fighter, Brawler Style','Increase damage of unarmed attack and spiked gauntlet'),
('Brutal Ferocity','PHB3','Minotaur, Ferocity','+2 attack and damage with attack granted by Ferocity'),
('Brutal Teamwork','MP','Strength 15, dragonborn ,rogue','+2 damage when adjacent to any ally'),
('Brutal Wound','MP','Rogue, Brutal Scoundrel,Sneak Attack','Deal additional ongoing damage with Sneak Attack'),
('Burden of Guardianship','PHB3','Wilden, Nature`s Aspect','Temporary hp when you use racial power and ally is nearby'),
('Burden of Rejuvination','PHB3','Wilden, Nature`s Aspect','Unconscious ally you can see heals when you use racial power'),
('Burning Blizzard','PHB','Int 13, Wis 13','+1 damage with acid or cold power'),
('Call to the Wild','HotFW','Druid','Exchange druid daily power for one use of summon natural ally'),
('Camouflage','MP','Wis 13, Ranger, trained inStealth','+5 to stealth outdoors when you have concealment'),
('Careful Summoner','AP','Con 13, Wizard','Summoned creatures gain +1 to defenses'),
('Cascading Rush','PHB3','-','Push adjacent enemy before or after bull rush'),
('Changeling`s Mark','MP2','Changeling, Fighter','Use changeling trick to mark adjacent enemies'),
('Channel Might','DP','Paladin','You gain +1 to melee attacks after you useChannel divinity'),
('Child of Fire','HotEC','Born of the Elements','Flames damage foe when you are bloodied or unconscious'),
('Child of Stone','HotEC','Born of the Elements','Gain resist 5 all when you use second wind on a stone surface'),
('Child of Storm','HotEC','Born of the Elements','+2 to next saving throw after taking elemental damage'),
('Child of the Sea','HotEC','Born of the Elements','Gain swim speed, other aquatic benefits'),
('Child of Wind','HotEC','Born of the Elements','Ignore difficult terrain when not wearing heavy armour'),
('Clarified Instincts','PHB3','Ardent, Mantle of Clarity','Mantle`s bonus to Insight and Perception equals Wis modifier'),
('Clarity of Spirit','DP','Kalashtar, Any Divine class','You or ally spends healing surge when you useBastion of mental clarity'),
('Cleanse the Madness','PHB3','Shardmind or Wilden','+2 or more damage against aberrant creatures'),
('Closing Advantage','AP','Swordmage','+1 to melee attacks and damage after hitting with a ranged or area power'),
('Closing Pledge','DP','Avenger, Censure of Pursuit,Oath of enmity','Shift closer to your Oath of enmity target after hitting it with ranged attack'),
('Cold Adaptation','Essentials','-','Resist 5 cold'),
('Combat Casting','AP','Swordmage','Ranged and area attacks don`t provoke after hitting with a melee power'),
('Combat Intuition','PHB3','-','+2 to Opportunity attack against enemy you miss'),
('Combat Medic','PHB2','Training in Heal','Stabilize the dying as minor action , +2 to Healchecks'),
('Combat Reflexes','PHB','Dex 13','+1 to opportunity attacks'),
('Combat Virtuoso','AP','Bard','Use Charisma for attack rolls of all multiclass powers'),
('Command the Darkness','MP','Drow, Warlord','Change how much Cloud of darkness obscures its area'),
('Constructing Serpent','MP2','Ranger, Beast Mastery(serpent)','While independant, beast immobilizes creatures'),
('Controlling Advantage','PHB3','Psion','Add 1 square to forced movement if you have combat advantage'),
('Coordinated Explosion','PHB2','-','+1 to attack rolls with blast or burst if ally is in area'),
('Coordinated Opportunity','MP','Ranger, Beast Mastery','+2 damage to opportunity attack if beast is adjacent'),
('Corellon’s Grace','PHB','Channel Divinity, must worshipCorellon','Use Channel Divinity to invoke Corellon’s Grace'),
('Courageous Heart','PrP','-','+2 to saving throws against charm of fear; increase by 1 for each ally with feat'),
('Crack the Mountain','PsP','Monk, Stone Fist','Enemy is slowed when hit by daily power'),
('Crashing Tempest Style','PHB3','Monk, Flurry of Blows','+2 to Flurry of Blows damage when wielding club'),
('Crippling Crush','PrP','Warden','Deal extra damage to targets you slow or immobilize with hammer or mace attacks'),
('Crossbow Expertise','Essentials','-','+1 to attack rolls with a crossbow , ignore partial and superior cover with crossbow attacks'),
('Crushing Earthstrength','PHB2','Warden , Earthstrength','Add Constition madifier to damage after second wind'),
('Crushing Mace','MP2','Any martial class','+2 damage with basic attacks using mace'),
('Cunning Ambusher','MP','Tiefling, Rogue','Combine infernal wrath with combat advantage for bonus to attack and damage rolls'),
('Curse of Io`s Blood','AP','Dragonborn, Warlock,Warlock`s Curse','Deal extra damage with curse when bloodied'),
('Cursed Advantage','AP','Drow, Warlock, Warlock`s Curse','Gain combat advantage against cursed enemies'),
('Dakshai`s Body-Mind Union','PHB3','Githzerai, Iron mind','Expend iron mind to gain saving throw with +5 bonus'),
('Dark Feasting','HoS','Revenant','Gain temporary HP when you deal damage withDark reaping'),
('Dark Fury','PHB','Con 13, Wis 13','+1 damage with necrotic or psychic power'),
('Darkfire Implement','AP','Drow, Any arcane class','Darkfire deals twice implement damage'),
('Darkfire Strike','MP2','Drow, Fighter','Use Darkfire when you hit a marked creature'),
('Darkfire Targeting','MP','Drow Ranger or drow Rogue','Target of your darkfire takes extra damage'),
('Darkfire Vitality','DP','Drow, Cleric','Allies gain temporary hp when they hit enemies under your Darkfire'),
('Deadeye Slinger','MP2','Rogue','Gain +3 proficiency bonus with slings and treat ashigh crit'),
('Deadly Draw','PHB3','-','Combat advantage against enemy you pull or slide adjacent'),
('Deadly Rage','PHB2','Barbarian','+1 damage while raging'),
('Deadly Rebuke','DP','Invoker, Covenant of Preservation','Gain more damage with preserver`s rebuke'),
('Deceptive Mind','PHB3','Battlemind, Battle Resilience','+2 to all defenses when using battle resilience'),
('Deep Gash','MP','Con 15, Fighter','Enemy takes -2 to saving throws against ongoing damage'),
('Deep Sage','PrP','Any Primal class, Trained inDungeoneering','+5 to Dungeoneering knowledge and aberrant creature monster knowledge checks, and gain fluency in Deep Speech'),
('Defensive Grace','DP','Cleric, Healer`s mercy','Bonus to defenses when you use Healer`s mercy'),
('Defensive Healing Word','DP','Cleric, Healing word (cleric)','Bonus to recipient`s defenses when you useHealing word (cleric)'),
('Defensive Mobility','PHB,Essentials','-','+2 to AC against opportunity attacks'),
('Defensive Resillience','MP','Con 13, Wis 13, Fighter','+1 to all defenses with second wind when bloodied'),
('Defensive Throw','MP2','Ranger, Marauder Fighting Style','Opportunity attacks provoked by thrown weapons are delayed'),
('Deft Eruption','PsP','Ardent, Ardent Eruption','+2 damage for Ardent eruption'),
('Demonbane','DP','Any Divine class','Powers that target undead also target elementals'),
('Demonbane Malediction','DP','Invoker, Covenant of Malediction','Elementals you hit with maledictor`s doom grant combat advantage to your ally'),
('Destructive Wizardry','AP','Dex 13, Wizard','+2 Damage if you hit two or more creatures'),
('Devilbane','DP','Any Divine class','Powers that target undead also target immortals'),
('Devoted Challenge','MP','Dwarf, Fighter, Combat Challenge','Bonus to melee basic attacks equal to Wis modifier'),
('Devoted Paladin','DP','Paladin, Lay on hands','Gain 1 healing surge, add cha modifier to Lay on hands'),
('Directed Bull Rush','PHB3','-','Slide your bull rush target instead of pushing'),
('Directing Inspiration','MP2','Warlord, Inspiring Word','Target of Inspiring word gains +1 attack or defense for ranged and area attacks'),
('Dirty Fighting','MP','Fighter or Rogue','+4 to melee damage against surprised enemies'),
('Disciple of Death','Essentials','Wis 13','+5 to death saving throws'),
('Disciple of Freedom','Essentials','Cha 13','+5 to check made as part of an escape action, can make saving throws against immobilization, slow, or restraint at the start of your turn'),
('Disciple of Inspiration','Essentials','Int 13','After making an at-will attack power that misses all targets, gain +1 to attack rolls until end of your next turn'),
('Disciple of Justice','Essentials','Cha 13','When using second wind, you can choose an adjacent ally to regain the hit point instead of yourself'),
('Disciple of Law','Essentials','Wis 13','+5 to check made to aid another, +1 to bonus given for successful aid'),
('Disciple of Light','Essentials','Wis 13','Spending a healing surge while bloodied grants each ally within 5 squares 3 temporary hit points'),
('Disciple of Lore','Essentials','Int 13','+1 to checks with skills you are trained in'),
('Disciple of Shadows','Essentials','Cha 13','Darkvision for 2 squares'),
('Disciple of Stone','Essentials','Con 13','Gain 5 temporary hit points when using a healing surge'),
('Disciple of Strength','Essentials','Str 13','+5 to next damage roll after using Second Wind'),
('Disciple of the Wild','Essentials','Dex 13','Shift up to three squares when using Second Wind'),
('Discipline Adept','PHB3','Psion, Discipline Focus','Use each Discipline Focus power twice per encounter'),
('Disciplined Wild Soul','PHB2','Sorcerer, Wild Magic','Roll twice to determine Wild Soul damage type'),
('Distant Advantage','PHB2','-','Gain combat advantage with ranged and area attack against flanked enemies'),
('Distracting Shield','PHB','Wis 15, fighter, Combat Challenge class feature','Target hit by Combat Challenge takes −2 to attack rolls'),
('Divine Approval','DP','Human, Any Divine class,Channel Divinity','Channel Divinity grants you a saving throw'),
('Divine Assault','DP','Half-orc, Paladin','Ally gains damage bonus against target of yourFurious assault'),
('Divine Distraction','DP','Avenger, Censure of Unity,Oath of enmity','Allies gain bonus damage to your Oath of enmitytarget when you are adjacent to target'),
('Divine Perseverance','DP','Human, Paladin','You gain +2 on your next attack after you succeed on a save'),
('Dodge Giants','PHB','Dwarf','+1 to AC and Reflex against attacks of Large or larger foes'),
('Dooming Action','AP','Warlock, Warlock`s Curse','Deal curse damage again with action point'),
('Double Scruitint','PsP','Psion, Shaped Conciousness','+3 to Insight and Perception while within 5 squares of conjured fragment'),
('Draconic Challenge','DP','Dragonborn, Paladin','Your Dragon breath places your divine sanction on enemies'),
('Draconic Spellcaster','AP','Dragonborn, Any arcane class','+1 to attacks that have same damage type as your breath weapon'),
('Dragging Flail','MP','Dex 15, Fighter','Using a flail, slide enemy as you knock it prone'),
('Dragonborn Channeling','MP2','Dragonborn, any martial class','Expend dragon breath for extra damage on a hit'),
('Dragonborn Frenzy','PHB','Dragonborn','+2 damage when bloodied'),
('Dragonborn Senses','PHB','Dragonborn','Low-light vision, +1 to Perception'),
('Dragonbreath Warrior','MP','Dragonborn, any martial class','Extra damage on melee attack after dragon breath'),
('Dragonclaw Mark','MP2','Dragonborn, Fighter','Marked creature takes extra damage from Dragon breath'),
('Draw First Blood','MP2','Any martial class','Undamaged enemy takes extra damage'),
('Drow Beast Mastery','MP','Drow, Ranger, Beast Mastery','Beast sees through your cloud of darkness'),
('Druid of Darkness','PrP','Drow, Druid, Wild shape','+2 damage when you have combat advantage in beast form'),
('Dual Implement Spellcaster','AP','Dex 13, Any arcane class','Add off-hand implement enhancement to damage rolls'),
('Durable','PHB,Essentials','-','Increase number of healing surges by 2'),
('Dwarf Battle Priest','DP','Dwarf, Cleric, Healing word (cleric)','Gain temporary hp when you use Healing word (cleric)'),
('Dwarf Stoneblood','MP','Dwarf, Fighter, Battlerager Vigor','Add half Con modifier to Battlerager Vigor temporary HP'),
('Dwarf Trapsmith','MP','Dwarf, rogue','+4 to Perception and Thievery for traps and locks'),
('Dwarven Weapon Training','PHB','Dwarf','+2 damage and proficiency with axes and hammers'),
('Eager Advance','Essentials','-','+4 to speed on first turn of an encounter'),
('Earthstrength Resilience','PrP','Warden, Earthstrength','Gain Resist 2 to all normal damage when you useSecond wind'),
('Echoes of Thunder','PHB2','-','+1 damage after you hit with thunder power'),
('Eladrin Soldier','PHB','Eladrin','+2 damage and proficiency with longswords andspears'),
('Eladrin Sword Wizardry','AP','Dex 13, Eladrin, Wizard','Use longsword as implement with wizard powers'),
('Eladrin Swordmage Advance','AP','Eladrin, Swordmage','Make basic attack after feystep'),
('Eladrin`s Challenge','MP2','Eladrin, Fighter','While you use longsword or spear, marked enemies take -3 penalty to attack rolls'),
('Elated Emotions','PHB3','Ardent, Mantle of Elation','Mantle`s bonus to Diplomacy and Intimidate equals Con modifier'),
('Elemental Barbarian','PrP','Genasi, Barbarian','+2 to attack roll when you use Firepulse or Promise of storm'),
('Elemental Blade Attunement','AP','Genasi, Swordmage','+1 to damage with acid, cold, fire, lightning, or thunder powers'),
('Elemental Blessing','DP','Genasi, Any Divine class','You or ally gains temporary hp when you use an elemental manifestation'),
('Elemental Challenge','DP','Genasi, Paladin','Your Divine challenge deals acid, cold, fire, lightning or thunder damage'),
('Elemental Echo','AP','Genasi, Any arcane class','+1 to attack, +2 to damage after using racial power'),
('Elemental Empowerment','AP','Genasi, Wizard','Add Strength modifier to damage with elemental keyword powers'),
('Elemental Rebuke','DP','Genasi, Invoker, Covenant of Preservation','Ally gains benefits when you use preserver`s rebuke'),
('Elven Arcane Precision','AP','Elf, Any arcane class','Reroll elven accuracy against all targets of a power'),
('Elven Beast Mastery','MP','Elf, Ranger, Beast Mastery','Beast benefits from wild step and Elven accuracy'),
('Elven Precision','PHB','Elf, elven accuracy racial power','+2 to reroll with elven accuracy'),
('Elven Sidestep','MP2','Elf, Fighter','Don`t provoke when moving away from your marked enemies'),
('Empowered Reaping','HoS','Revenant','+2 or more bonus damage with Dark reaping'),
('Empowering Shadows','AP','Warlock, Shadow Walk','+1 to damage when you have concealment'),
('Enduring Mountain','PrP','-','Regain 2 additional hp with healing surge; increase by 1 for each ally with feat'),
('Enlarge Spell','AP','Wis 13, Wizard','-2 to damage to increase size of blast or burst by 1'),
('Enlarged Dragon Breath','PHB','Dragonborn, dragon breathracial power','Dragon breath becomes blast 5'),
('Enraged Boar Form','PHB2','Druid, wild shape','+1 attack, +2 damage when charging in beast form'),
('Escape Artist','PHB','Trained in Acrobatics','Escape a grab as minor action, +2 to Acrobatics'),
('Evade and Strike','DP','Halfling, Avenger, Oath of enmity','If your Oath of enmity target misses due to Second chance, you gain +2 to damage against target'),
('Exchange Power','PHB3','Psion, Send Thoughts','Transfer 1 power point to ally when using Send Thoughts'),
('Executioner of Undeath','HoS','-','Reroll damage against undead with axes and heavyblades'),
('Expanded Spellbook','PHB','Wis 13, wizard','Add additional daily spells to spellbook'),
('Expert Combat Leader','MP2','Warlord, Combat Leader','Combat Leader initiative bonus increases to +3'),
('Expert Ritualist','PHB2','Ritual Caster','+2 bonus to ritual skill checks'),
('Expert Tracker','MP','Wis 13, Ranger, Trained inPerception','+5 to your perception checks to find tracks and to the DC for others to find your tracks'),
('Explosive Leader','MP2','Genasi, Warlord, Earthshock,Firepulse or Promise of storm','Allies gain +2 to hit enemy hit by your racial power'),
('Extended Prescience','AP','Bard, Virtue of Prescience','Ally`s bonus to defense lasts until the end of the ally`s next turn'),
('Eyes of the Spirits','PrP','Elf, Any Primal class','Allies affected by Group Awareness ignore -2 concealment penalty'),
('Fading Sneak','HotFW','Gnome, Fade Away, trained inStealth','Reroll a Stealth check'),
('Fading Spirit','PrP','Gnome, Shaman','Spirit companion is hidden while you`re hidden'),
('Fading Target','HotFW','Gnome, Fade Away','Use [[fade away when an enemy misses'),
('Familiar`s Vitality','HotFW','Arcane Familiar','Your familiar improves your second wind'),
('Fanged Magic','AP','Longtooth shifter, Any arcaneclass','Deal extra damage while longtooth shifting'),
('Far Shot','PHB','Dex 13','Increase projectile weapon range by 5 squares'),
('Far Throw','PHB','Str 13','Increase thrown weapon range by 2 squares'),
('Fast Runner','PHB','Con 13','+2 to speed when you charge or run'),
('Fearless Seeker','MP2','Goliath, Ranger, Hunter`s Quarry','Use Stone`s endurance when hit by quarry`s melee attack'),
('Fearsome Charge','PrP','Barbarian, Rageblood Vigor','Target of Swift charge is also pushed 1'),
('Fearsome Host','PrP','-','+2 to Intimidate checks; increase by 1 for each ally with feat'),
('Fearsome Wrath','DP','Half-orc, Avenger, Oath of enmity','Use Furious assault to penalise attacks of yourOath of enmity target'),
('Feral Advance','PsP','Elf, Battlemind, Speed of Thought','Dex modifier determines speed of thought distance'),
('Feral Fey Step','PrP','Eladrin, Any Primal class','Use Fey step again the first time you`re bloodied'),
('Ferocious Rebuke','PHB','Tiefling, infernal wrath racial power','Push 1 square with infernal wrath'),
('Ferocious Tiger Form','PHB2','Druid, wild shape','+2 damage with combat advantage in beast form'),
('Fey Blades','MP','Eladrin, Fighter, Tempest Technique','+1 damage with longsword in each hand'),
('Fey Bond','HotFW','Trained in Arcana','Gain Elven, +2 Bluff and Diplomacy checks'),
('Fey Cantrip','HotFW','Fey origin or Fey Bond','Gain a cantrip'),
('Fey Command','MP','Eladrin, Warlord, Tactical Presence','Ally can teleport before or after attacking'),
('Fey Duelist','HotFW','Eladrin, Fey Step','Use fey step to gain combat advantage'),
('Fey Fate','DP','Elf, Avenger, Oath of enmity','If you hit your Oath of enmity target with Elven accuracy you gain +2 to damage against target'),
('Fey Preserver','DP','Eladrin, Invoker, Covenant of Preservation','Teleport ally 2 squares when you use preserver`s rebuke'),
('Fey Thievery','HotFW','Eladrin, Fey Step','Use fey step to perform Thievery checks at range'),
('Fey Trickster','PHB2','Gnome','Gain mage hand and prestidigitation as encounter powers'),
('Feyborn Charm','AP','Eladrin or Gnome, Bard','Bonus to attack and damage with charm powers, +1 to Bluff, Diplomacy'),
('Feyborn Companion','MP','Eladrin, Ranger, Beast Mastery','Beast gains fey origin, charm bonus and feystep'),
('Feyborn Fortune','DP','Gnome, Cleric, Divine fortune','Divine fortune also affects one ally'),
('Feyborn Pursuer','DP','Eladrin, Avenger, Oath of enmity','Teleport extra 5 squares with Fey step if you end adjacent to your Oath of enmity target'),
('Feyborn Shroud','MP2','Gnome, Warlord, Int 13,Inspiring word','Target of inspiring word gains concealment'),
('Feywild Advance','PsP','Eladrin, Battlemind, Blurred Step','Teleport int instead of shifting with Blurred step'),
('Fickle Servant','DP','Changeling or Doppelganger, Any Divine class','+3 on religion checks and you can choose feats from any domain'),
('Fiendish Companion','MP','Tiefling, Ranger, Beast Mastery','Beast gains resist fire'),
('Firedancer','HotEC','Born of the Elements','Gain resist 5 fire; deal fire damage after using second wind'),
('Flank on the Run','MP2','Ranger, Running Attack','Don`t provoke when moving around enemy and remaining adjacent'),
('Fluid Motion','PsP','Monk','+1 to speed'),
('Focus the Spirits` Lives','PrP','Deva, Any Primal class','Roll dl0 instead of d6 for Memory of a thousand lifetimes on some rolls'),
('Focused Mind','PHB3','-','+4 to saving throws against dazing and stunning effects'),
('Focusing Spellfury','AP','Sorcerer','+2 to damage after hitting multiple foes with at-will power'),
('Formation Fighting','MP2','Any martial class','Bonus to opportunity attacks when allies near an enemy'),
('Four Winds','PrP','-','+2 to Athletics checks; increase by 1 for each ally with feat'),
('Four-Armed Flurry','DSCG','Thri-kreen, Flurry of blows','One target of Flurry of blows takes extra damage'),
('Friendly Deception','AP','Bard, Words of friendship','Apply Words of friendship bonus to Bluff check'),
('Frozen Soul','HoS','Con 13 or Wis 13','Cold resistance and additional Will defense'),
('Furious Charge','MP2','Half-orc, Ranger, Hunter`s Quarry','Expend Furious assault to re-roll charge attack'),
('Furious Devotion','DP','Half-Orc, Any Divine class,Channel Divinity','+2 damage with divine powers after you useChannel Divinity'),
('Gestalt Anchor','PsP','Kalashtar, Ardent Mantle','You and allies gain +2 to initiative checks; allies gain +2 to all defenses when you drop to 0 power points'),
('Ghost Eyes','HoS','Wis 13','+2 to attack rolls against invisible creatures, +5 to perception to find hidden creatures'),
('Ghost Feint','HotFW','Gnome, Ghost Sound, trained in Bluff','+5 to Bluff when you use ghost sound'),
('Ghost Scorpion Strike','HoS','-','Necrotic and poison powers ignore insubstantial'),
('Gnome Phantasmist','AP','Gnome, Wizard','+1 to attack and damage with illusion powers'),
('Gnome Weapon Training','MP2','Gnome, any martial class','Proficiency and damage bonus with hammers andpicks'),
('Goliath Crusher','MP2','Goliath, Fighter','When attacking a marked creature, your mace hasHigh crit'),
('Goliath Greatweapon Prowess','PHB2','Goliath','Gain proficiency, +2 damage with two-handed melee weapons'),
('Gorebrute Charge','PHB2','Longtooth shifter','+3 damage on charge attacks during longtooth shifting'),
('Goring Boar','MP2','Ranger, Beast Mastery (boar)','While independant, beast pushes creatures'),
('Goring Shove','PHB3','Str 15, Minotaur, Goring charge','Push target 1 square after goring charge'),
('Grasping Ensnarement','AP','Swordmage, Aegis of ensnarement','Target of Aegis is slowed'),
('Great Fortitude','Essentials','-','+2 Fortitude'),
('Grounding Shot','PHB3','-','Your ranged attacks hit and damage prone targets more easily'),
('Group Assault','MP','Half-elf, Fighter','Allies gain +1 damage against your marked target'),
('Group Defense','DP','Half-elf, Paladin','Allies gain +1 to defenses against creatures you mark'),
('Group in Motion','PsP','Half-elf, Battlemind, Speed of Thought','Allies adjacent to you shift with speed of thought'),
('Group Insight','PHB','Half-elf','Grant allies +1 to Insight and initiative'),
('Group Quarry','MP','Half-elf, Ranger','Allies gain +1 damage against your quarry'),
('Group Rattling','MP','Half-elf, Rogue, trained inIntimidate','Allies gain +1 to attack rolls against your enemy affected by rattling power'),
('Group Stealth','PHB2','Gnome','Neaby allies gain +2 to Stealth checks'),
('Guaranteed Retribution','PHB2','Avenger, Censure of Retribution, oath of emnity','+1 to next attack roll against oath of emnity target when another enemy hits you'),
('Guardian of the Towering Oak','HotFW','Hamadryad, Hamadryad Aspects','Reroll a Diplomacy or Intimidate Check'),
('Guide the Shot','MP2','Elf, Warlord','Allies ignore difficult terrain when you let them shift'),
('Guiding Step','MP2','Elf, Warlord','Allies ignore difficult terrain when you let them shift'),
('Hafted Defense','PHB3','-','+1 AC and Reflex while wielding polearm or staff in two hands'),
('Half-Elf Spirit Speaker','PrP','Half-elf, Any Primal class','+1 to all defenses for you and allies when you`re first bloodied; +1 to Insight and Nature for allies'),
('Halfling Agility','PHB','Halfling, second chance racial power','Attacker takes a −2 penalty with second chancereroll'),
('Halfling Stalwart','MP','Halfling, Fighter','+1 to attack rolls against Large or larger marked targets'),
('Hammering Iron','PHB3','-','Push target after opportunity attack when using hammer'),
('Harmony of Erathis','PHB','Channel Divinity, must worshipErathis','Use Channel Divinity to invoke Harmony of Erathis'),
('Harrying Raptor','MP2','Ranger, Beast Mastery (raptor)','While independant, beast makes creatures grant combat advantage'),
('Harrying Step','PsP','Battlemind, Blurred Step,persistent harrier','Teleport instead of shift with Blurred step'),
('Haunted Darkness','PsP','Drow, Psion, Cloud of darkness','+1 to attacks with augmented at-will powers when bloodied'),
('Haunting Sounds','PsP','Gnome, Ghost sound, Psionic Augmentation','Use Ghost sound as at-will; augment to gain combat advantage'),
('Headsman`s Chop','PHB3','-','5 extra damage to prone target when using axe or heavy blade'),
('Heat Adaptation','Essentials','-','Resist 5 fire'),
('Healer`s Implement','DP','Cleric','Add holy symbol enchantment bonus to healing powers'),
('Healing Fist','PsP','Githzerai, Monk','Gain damage bonus with second wind'),
('Healing Hands','PHB','Paladin, lay on hands power','Add Cha modifier to damage healed with lay on hands'),
('Healing Step','DP','Eladrin, Any Divine class','Grant temporary hp with Fey step'),
('Heartening Surge','PHB3','Ardent, Ardent surge','Increase ardent surge bonus to defenses or attacks by 1'),
('Heavy Armor Agility','Essentials','Str 15 or Con 15','Ignore speed penalty for wearing heavy armor'),
('Heavy Blade Expertise','Essentials','-','+1 to attack rolls with a heavy blade , +2 to all defense against opportunity attacks while welding a heavy blade'),
('Hellfire Blood','PHB','Tiefling','+1 attack and damage with fire and fear powers'),
('Helpful Hint','PsP','Halfling, Psion, Send Thoughts','Expend send thoughts to let ally reroll saving throw'),
('Herbalist','PrP','Trained in Dungeoneering orNature, trained in Heal','+5 to Heal checks for disease; gain Brew Potionritual.'),
('Hidden Channeling','DP','[[Gnome], Any Divine class,Channel Divinity','Channel Divinity grants you concealment'),
('Hidden Pulse','MP2','Genasi, rogue, firepulse,Sneak Attack','Extra damage with firepulse if you have combat advantage'),
('Hidden Sniper','Essentials','-','Combat advantage with ranged attacks when partially concealed'),
('Hide Armour Expertise','PrP','Any Primal class, Con 15, proficiency with hide armour','Substitute Con modifier for Dex or Int to determineAC'),
('High Elf Kin','HotFW','Elf, Elven Accuracy','Teleport 2 after elven accuracy, +2 to Arcana checks'),
('Hip Throw','MP2','Fighter, Brawler style','Knock enemy prone when you crit on a grab or a martial power that grabs'),
('Hobbling Strike','MP2','Ranger, Hunter`s Quarry','Give up 1 die of Hunter`s Quarry damage to slow enemy'),
('Holy Resolve','DP','Warforged, Cleric','Bonus to healing you grant after using warforged resolve'),
('Holy Savagery','DP','Shifter, Any Divine class,Channel Divinity','Channel Divinity grants you +1 to melee attacks when bloodied'),
('Holy Speech','DP','Any Divine class, fluent in Supernal','Extra success in skill challenges using Bluff, Diplomacy or Intimidate'),
('Holy Symbol Expertise','HoS','-','+1 feat bonus to implement attacks and cannot grant combat advantage'),
('Honeyed Words','HotFW','Satyr, Lure of Enchantment','Reroll a Bluff or Diplomacy check'),
('Human Beast Mastery','MP','Human, Ranger, Beast Mastery','Beast gains +1 to all defenses'),
('Human Ingenuity','PsP','Human, Psionic Augmentation','Spend action point to attack, regain 1 power point'),
('Human Nature Lore','PrP','Human, Any Primal class','Roll twice for Endurance or Nature checks'),
('Human Perseverance','PHB','Human','+1 to saving throws'),
('Hunter of Wind and Wave','MP','Genasi, Ranger','+2 to movement with swiftcurrent or windwalker'),
('Hunter`s Aim','MP','Ranger, Hunter`s Quarry','Ignore Quarry`s cover or concealment'),
('Hunting Thri-Kreen','DSCG','Thri-kreen, Hunter`s Quarry','Deal damage to adjacent foe when using Hunter`s Quarry'),
('Hurl Weapon','PrP','Barbarian','Treat one-handed off-hand weapons as heavy thrown'),
('Hybrid Talent','PHB3','Hybrid','Gain a hybrid talent option from either hybrid class'),
('Immortal Warding','AP','Deva, Swordmage,Swordmage Warding','Swordmage Warding persists while you`re unconscious, resistance bonus'),
('Immovable Resilience','PsP','Battlemind, Battle resilience','Ignore forced movement after using battle resilience'),
('Impaling Thrust','PrP','Warden','Treat critical as normal hit to immobilize target when using heavy blade or spear'),
('Impending Victory','PHB3','-','+1 attack with at-will powers against bloodied creatures'),
('Implement Expertise','PHB2','-','+1 to attack rolls with chosen implement'),
('Implement Focus','Essentials','-','Choose an implement you are proficient with, +1 damage with implement'),
('Improved Armor of Faith','PHB2','Avenger, armor of faith','Increases armor of faith bonus to AC'),
('Improved Aspect of Nature','PHB3','Wilden, Nature`s Aspect','Gain additional benefit from use of your racial power'),
('Improved Bravura','MP','Warlord, Bravura Presence','Ally gains +1 to attack rolls or speed with Bravura Presence'),
('Improved Bull Rush','PHB2','Str 13, Con 13','+4 to bull rush attacks'),
('Improved Cunning Sneak','MP2','Cunning Sneak, rogue','Move 1 square less to gain benefit of Cunning Sneak feature'),
('Improved Dark One’s Blessing','PHB','Con 15, warlock, infernal pact','Pact boon grants 3 additional temporary hit points'),
('Improved Defenses','Essentials','-','+1 Fortitude, Reflex, & Will, +2 at level 11, +3 at level 21'),
('Improved Dragon Soul','PHB2','Sorcerer, Dragon Magic','Increase Dragon Soul resistance by 2'),
('Improved Fate of the Void','PHB','Con 13 or Cha 13, warlock,star pact','Pact boon grants additional +1 bonus to die roll'),
('Improved Grab','PHB2','Str 13','+4 to grab attacks'),
('Improved Inevitable Shot','PHB3','Seeker, Inevitable shot','Inevitable shot attack ignores cover and concealment'),
('Improved Initiative','PHB,Essentials','-','+4 to initiative checks'),
('Improved Insight','MP2','Warlord, Insightful Presence','Insightful Presence can grant greater bonus to single defense'),
('Improved Inspiration','MP','Warlord, Inspiring Presence','Ally gains +2 hp with Inspiring Presence'),
('Improved Inspiring Word','MP','Warlord','Add Cha modifier to Inspiring word hp restored'),
('Improved Majestic Word','PHB2','Bard , majestic word','Target of majestic word gains temporary hp'),
('Improved Misty Step','PHB','Int 13, warlock, fey pact','Pact boon grants additional 2 squares of teleport'),
('Improved Monk Unarmed Strike','PHB3','Monk , Unarmed Combatant','Damage die of your unarmed strike improves to 1d10'),
('Improved Rageblood Vigor','PHB2','Barbarian, Rageblood Vigor','Gain 5 temporary hp from Rageblood Vigor'),
('Improved Resources','MP','Warlord, Resourceful Presence','Ally gains +2 damage and temporary HP from resourceful presence'),
('Improved Roar of Triumph','PHB2','Barbarian, Thaneborn Triumph','Roar of triumph burst is larger, grants you +2 damage'),
('Improved Skirmishing','MP2','Warlord, Skirmishing Presence','Ally benefiting from skirmishing presence gains +1 to attack'),
('Improved Speed of Thought','PHB3','Battlemind, Speed of Thought','Your Speed of Thought movement increases by 2 squares'),
('Improved Swordmage Warding','AP','Dex, Swordmage, Swordmage Warding','Increase AC bonus from Swordmage Warding'),
('Improved Tactics','MP','Warlord, Tactical Presence','Ally gains +1 to attack rolls with Tactical Presence'),
('Improved Vigor','MP','Fighter, trained in Endurance','Invigorating powers grant +1 temporary HP'),
('Improvised Missile','PrP','Barbarian','+2 to attack and damage with thrown improvised melee'),
('Inescapable Shot','PHB3','Seeker, Inevitable Shot','Inevitable shot targets enemy within 10 squares of missed target'),
('Inescapable Hold','MP2','Fighter, Brawler style','Resist grab attempts with fortitude'),
('Infernal Blessing','DP','Tiefling, Any Divine class','Ally regains hp when you use Infernal wrath'),
('Infernal Clamour','AP','Tiefling, Bard','Allies gain +1 to hit against Infernal wrath target'),
('Infernal Malediction','DP','Tiefling, Invoker, Covenant of Wrath','Your attacks gain fear keyword when you useInfernal wrath'),
('Infernal Might','MP2','Tiefling, any martial class','Extra damage with infernal wrath'),
('Infuriating Escape','AP','Halfling, Bard','Enemy grants Combat advantage after second chance'),
('Inner Compass','PrP','Trained in Dungeoneering orNature','Roll twice for Dungeoneering and Nature checks in natural environment'),
('Insightful Preservation','PHB2','Invoker, Covenant of Preservation','Preserver`s rebuke grants temporary hp'),
('Inspirational Attacker','MP2','Warlord, Inspiring Word','Inspiring word heals extra hp if target is adjacent to an enemy you hit'),
('Inspired Defense','MP','Human, Warlord','Ally gains +1 to all defences with inspiring word'),
('Inspired Recovery','PHB','Warlord, Inspiring Presence class feature','Grant ally saving throw with Cha modifier bonus'),
('Inspired Tactics','MP','Half-elf, Warlord, Inspiring Presence','Ally gains +1 to attack rolls when spending action point'),
('Inspiring Breath','MP2','Dragonborn, Warlord, Archer Warlord','Allies gain +5 damage against enemies hit byDragon breath'),
('Into the Fray','MP','Rogue, First Strike','+1 to Speed and to melee attack rolls in surprise round'),
('Intelligent Blademaster','FRPG','Swordmage','Use Intelligence instead of Strength on your basic attacks'),
('Invigorating Pursuit','PHB2','Avenger, Censure of Pursuit,oath of enmity','Gain +2 AC and damage when you charge oath of enmity target'),
('Invigorating Spirit','PrP','Shaman, Healing spirit','Spirit companion is hidden while you`re hidden'),
('Invoke Resilience','DP','Human, Invoker','Ally gains +1 to next saving throw when you use a divine power'),
('Invoke Teamwork','DP','Half-elf, Invoker','Ally gains +1 to defenses when you use a divine power'),
('Invoker Defense','PHB2','Invoker','+2 AC when you hit nearby enemy'),
('Io`s Roar','PsP','Dragonborn, Dragon breath, any psionic class','Dragon breath confers vulnerable 5 psychic'),
('Ioun`s Poise','PHB','Channel Divinity, must worshipIoun','Use Channel Divinity to invoke Ioun`s poise'),
('Iron Parry','PsP','Monk, Iron Soul','+1 to AC with weapon, no armour, no shield'),
('Iron Resolve of Zerthadlun','PHB3','Githzerai','+2 to saving throws if you have at least 1 power point'),
('Iron Trap','PsP','Githzerai, Battlemind, iron mind','Gain combat advantage when enemy misses because of iron mind'),
('Iron Will','Essentials','-','+2 Will'),
('Jack of All Trades','PHB,Essentials','Int 13','+2 to untrained skill checks'),
('Jagged Force','PsP','Shardmind, Psion','+2 to damage with force powers'),
('Keeper of Storm','MP','Genasi, Fighter, Combat Challenge','Deal thunder or lightning damage when using stormsoul'),
('Ki Focus Expertise','HotEC','-','+1 to attack rolls with ki focuses, +1 damage against bloodied enemies'),
('Kinetic Reel','DSCG','Battlemind, Wild focus','Pull target of Wild focus 2 extra squares'),
('Kord`s Resilience','DP','Goliath, Any Divine class','Stone`s endurance extends to adjacent allies'),
('Kord’s Favor','PHB','Channel Divinity, must worshipKord','Use Channel Divinity to invoke Kord`s Favor'),
('Leading Fire','MP','Elf, Warlord, Combat Leader','Allies gain +1 to ranged attack rolls against target'),
('Legioncaller of Moil','HoS','Any Shadow Summoningpower','+1 to attack and defenses of shadow summoned creatures'),
('Lend Might','MP','Warlord','+1 to attack rolls of attacks you grant'),
('Lend Strength','MP2','Warlord','Ally gains +2 damage with basic attack you grant'),
('Lethal Hammer Training','MP2','Dwarf, rogue','Use hammers with Sneak Attack and rogue powers'),
('Lethal Hunter','PHB','Ranger, Hunter’s Quarry class feature','Hunter’s Quarry damage dice increase to d8s'),
('Liberating Shard Swarm','PHB3','Shardmind, Shard swarm','Make saving throw when you use shard swarm'),
('Lifespirit Vigor','PrP','Warden, Lifespirit','Another ally makes a saving throw when you use second wind'),
('Light Blade Expertise','Essentials','-','+1 to attack rolls with a light blade , +1 damage when using light blade and have combat advantageagainst target'),
('Lightning Reflexes','Essentials','-','+2 Reflex'),
('Light Step','PHB','Elf','Add to overland speed of group, +1 to Acrobaticsand Stealth'),
('Lingering Wrath','MP','Tiefling, Fighter, Combat Challenge','Bonuses from Infernal wrath last as long as your mark.'),
('Linguist','PHB,Essentials','Int 13','Learn three new languages'),
('Long Jumper','PHB','Trained in Athletics','Make standing jumps as if from a running start, +1 to Athletics'),
('Longsword Finesse','MP','Eladrin, Rogue','Treat longsword as light blade'),
('Longtooth Fury','MP2','Longtooth Shifter, Fighter','+4 damage against marked creatures while you`re shifting'),
('Longtooth Spirit Shifter','PrP','Longtooth Shifter, Any Primalclass','Longtooth shifting regeneration increases by 2'),
('Lost in the Crowd','PHB','Halfling','+2 to AC when adjacent to at least two larger enemies'),
('Low Crawl','PHB3','-','You can shift while prone'),
('Low-Light Adaptation','Essentials','-','Gain low-light vision'),
('Lucky Skirmisher','MP','Halfling Ranger or halflingRogue','You are harder to hit when you run'),
('Lucky Start','PHB3','-','Make first attack roll twice if your initiative check is highest'),
('Lure of Iron','PHB3','Battlemind, Mind spike','Slide target of Mind spike'),
('Magic of the Ages','AP','Deva, Any arcane class','+1 to attack roll with memory of a thousand lifetimes'),
('Magic of the Mists','AP','Gnome, Any arcane class','Retain fade away effect when you attack'),
('Majestic Presence','DP','Deva, Any Divine class','Adjacent allies gain resist 3 necrotic and resist 3 radiant'),
('Manifest Healing','PrP','Genasi, Any Primal class','Gain 5 temporary hp when you use a racial power'),
('Manticore`s Fury','MP2','Ranger','Extra damage when mixing melee and ranged attacks'),
('Mantle of Readiness','PHB3','Ardent, Ardent Mantle','You and nearby allies gain +2 speed at start of combat'),
('Mantle of Understanding','PsP','Ardent, Ardent Mantle','Allies gain +2 to saving throws when you save'),
('Mark of the Infernal','DP','Tiefling, Paladin','You can use Divine sanction when your infernal wrath attack hits'),
('Marked Fury','MP2','Fighter','Extra penalty to marked enemy`s attack'),
('Markings of the Blessed','PHB2','Goliath','Roll twice for first saving throw each encounter'),
('Markings of the Elements','PrP','Goliath, Any Primal class','Give up resistance to all damage from stone`s endurance to gain resist 5 to chosen damage type'),
('Markings of the Predator','PrP','Goliath, Any Primal class','+1 to all defenses when you bloody a creature'),
('Markings of the Victor','PHB2','Goliath','Roll twice for first attack roll each encounter'),
('Martial Adaptation','MP2','Any martial class','Swap daily power after extended rest'),
('Martial Alacrity','MP','Charisma 15, any martial class','+2 to initiative and shift quickly during your first turn'),
('Martial Dilettante','MP2','Half-elf, any martial class','Use Dilettante power twice per encounter'),
('Martial Flexibility','MP2','Any martial class','Swap martial utility power after extended rest'),
('Martial Freedom','MP','Wisdom 13, any martial class,Endurance trained','+5 to saving throws against the slowed andimmobilized conditions'),
('Martial Ploy','MP2','Any martial class','Ally rolls twice on attack if you use aid another'),
('Martial Readiness','MP2','Any martial class','Swap martial at-will attack power after extended rest'),
('Martial Versatility','MP2','Any martial class','Swap martial encounter attack power afterextended rest'),
('Martyr`s Surge','PsP','Ardent, Argent Surge','While you are bloodied, Ardent surge hit points regained by target increase by 1d6'),
('Master at Arms','Essentials','-','+1 to weapon attack rolls, sheathe a weapon and draw a new one with a minor action'),
('Master of Rumbling Earth','MP','Genasi, Fighter','Bonuses to attack rolls and damage withearthshock'),
('Mauling Bear','MP2','Ranger, Beast Mastery (bear)','While independant, beast grabs creatures'),
('Melee Training','PHB2','-','Change ability used for melee basic weapon attacks'),
('Melora’s Tide','PHB','Channel Divinity, must worshipMelora','Use Channel Divinity to invoke Melora`s Tide'),
('Memory of a Thousand Battles','MP2','Deva, Fighter','Expend Memory of a thousand lifetimes to re-roll attacks with reliable power'),
('Menacing Thug','MP2','Half-orc, rogue','Gain combat advantage on hits with furious assault'),
('Midnight Stalker','PrP','-','+2 to Stealth checks; increase by 1 for each ally with feat'),
('Mighty Challenge','DP','Paladin, Divine challenge','Divine challenge deals Str extra radiant damage'),
('Mindbite Scorn','DSCG','Warlock, Sorcerer-king pact','Curse deals 1d6 extra psychic damage'),
('Mindlink','PsP','Psion, Send Thoughts','Use send thoughts to ignore cover and concealment'),
('Miryath`s First Strike','PHB3','Wisdom 13, Githzerai','Extra damage against creature that has not yet acted'),
('Moradin’s Resolve','PHB','Channel Divinity, must worshipMoradin','Use Channel Divinity to invoke Moradin`s Resolve'),
('Mountain Hammer Spellcasting','AP','Goliath, Any arcane class','Ignore resistances after using stone`s endurance'),
('Mounted Combat','PHB','-','Gain access to the special abilities of your mount'),
('Nature`s Roots','HotFW','Wilden, Nature`s Aspect','Use Nature`s Aspect to create difficult terrain'),
('Nature`s Sentinel','PsP','Wilden, Battlemind, Nature`s Aspect, Battlemind`s demandBlurred Step, Mind spike','Battlemind powers gain benefit corresponding to your Nature`s Aspect'),
('Nimble Blade','PHB','Dex 15','+1 to attacks with light blade and combat advantage'),
('Nimble Companion','MP','Halfling, Ranger, Beast Mastery','Beast gains +2 AC against opportunity attacks'),
('Nimble Dodge','MP2','Halfling, any martial class','Second chance gives -5 penalty and enemy can`t crit'),
('Nimble Runner','PHB3','-','+2 Reflex when you run, and don`t grant combat advantage'),
('Nimble Spellcaster','AP','Halfling, Dex 13, Any arcaneclass','Area arcane powers don`t provoke opportunity attacks'),
('Nimbus of Light','DP','Any Divine class','Allies gain +1 to attack with radiant powers after you use a radiant encounter or daily power'),
('Oath Strike','DP','Avenger, Oath of enmity','Mark your Oath of enmity target'),
('Offensive Resilience','MP','Dex 13, Wis 13, Fighter','+1 to attack roll after using second wind when bloodied'),
('Oncoming Storm','PHB2','-','Hit with lightning power to gain +1 on thunderattacks'),
('Opportunistic Accuracy','MP','Wis 13, Elf, Fighter','Retain Elven accuracy when you miss'),
('Opportunistic Shove','PHB3','-','Bull rush when you make Opportunity attack'),
('Opportunity Knocks','MP2','Rogue','Gain combat advantage after some opportunity attacks'),
('Orb Expertise','Essentials','-','+1 to attack rolls with an orb, +1 to squares of forces movement using an orb'),
('Orbiting Object','PHB3','Psion, Far Hand','Sustain far hand for free if target is adjacent or in your space'),
('Outraged Vengeance','PsP','Ardent, Ardent outrage','Allies gain +2 damage against Ardent outragetarget'),
('Overrun Critical','MP2','Any martial class','Critical hit on charge pushes enemy and knocks itprone'),
('Pacifist Healer','DP','Cleric','Your healing powers are better, but you`re punished for damaging bloodied foes'),
('Past Soul','HoS','Revenant','Gain racial power of past life race'),
('Path to Clarity','PsP','Githzerai, Ardent, Ardent surge','Ardent surge allows saving throw to end some effects'),
('Pelor’s Radiance','PHB','Channel Divinity, must worshipPelor','Use Channel Divinity to invoke Pelor’s Radiance'),
('Phantom Echoes','AP','Cha 13, Wizard','Gain combat advantage against target hit by illusion power'),
('Plant`s Sap','HotFW','Wilden','Ignore need for food, gain extended rest in 4 hours, +2 to saving throws for ongoing damage'),
('Pointed Step Style','PHB3','Monk, Flurry of Blows','Attack from 2 squares away when using spear withFlurry of Blows'),
('Polearm Expertise','MME','-','+1 per tier to polearm weapon attack rolls, and +2 to AC vs. charges while wielding a two-handed polearm'),
('Polearm Flanker','PHB3','-','Flank from 1 square away when using a polearm'),
('Polearm Momentum','MP','Dex 15, Wis 15, Fighter','Knocked pushed or slid enemy prone with polearm'),
('Potent Challenge','PHB','Con 15, fighter, Combat Challenge','Add Con modifier damage to target hit with Combat Challenge'),
('Potent Rebirth','PHB2','Deva','+2 to attack and damage if reduced to 0 hp'),
('Pouncing Cat','MP2','Ranger, Beast Mastery (cat)','While independant, beast attacks again after charge hits'),
('Power Attack','PHB','Str 15','+2 or +3 damage per tier for −2 to attack'),
('Power Cascade','PsP','Psion','Extra force or psychic damage after hitting with daily attack'),
('Power Throw','PHB3','Str 15','+2 or damage per tier for -2 to attack with heavy thrown weapon.'),
('Powerful Charge','PHB','Str 13','+2 damage, +2 to bull rush on a charge'),
('Practiced Prodigy','MP2','Practiced Study, any martialclass','Learn two martial practices , add more as you gain levels'),
('Practiced Study','MP2','Any martial class','Learn and use martial practices'),
('Precise Fangs','PrP','Shaman, Stalker Spirit','+2 to attack rolls when you use Spirit`s Fangs'),
('Precise Hunter','PHB','Wis 15, ranger, Hunter’s Quarry','Allies gain +1 attack against target hit by critical hit'),
('Precise Mind','PHB3','Psion','+1 attack with unaugmented psionic at-wills after you hit with augmented Psionic attack power'),
('Precision Throw','MP2','Any martial class','Use Dexterity for ranged basic attacks with thrown weapons'),
('Predator`s Burst','PrP','Druid, Primal Predator, Wild shape','While in beast form, +2 speed, +1 to attack while charging'),
('Predatory Action','MP','Ranger, Hunter`s Quarry','Deal hunter`s quarry damage again with an action point'),
('Predatory Magic','AP','Razorclaw shifter, Any arcaneclass','Shift as free action while razorclaw shifting'),
('Prescient Fortification','AP','Bard, Virtue of Prescience','Ally gains greater bonus to his or her defense'),
('Preserver`s Call','DP','Kalashtar, Invoker, Covenant of Preservation','Pull allies 1 square closer when you use a daily divine power'),
('Preserving Concealment','DP','Gnome, Invoker, Covenant of Wrath','Grant concealment to ally when you usepreserver`s rebuke'),
('Press the Advantage','PHB','Cha 15, rogue','Retain combat advantage with a critical hit'),
('Primal Breath','PrP','Dragonborn, Warden','Mark each target of your Dragon breath'),
('Primal Fury','PHB2','Druid, Primal Predator','+1 to attacks with primal powers against bloodiedenemies'),
('Primal Halfling Counterattack','PrP','Halfling, Any Primal class','+4 to damage against target of second chance'),
('Primal Instinct','PHB2','Druid, Primal Guardian','Ally can reroll initiative'),
('Primal Resilience','PrP','Half-orc, Any Primal class','Give up resistance to all damage from stone`s endurance to gain resist 5 to chosen damage type'),
('Prime Burst','PHB3','Prime Shot','Prime Shot benefit also applies to area burst attacks'),
('Prime Strike','MP','Ranger','+1 to melee attack rolls when no others are near your target'),
('Protector Spirit Adept','PHB2','Shaman, Protector Spirit','Allies Adjacent to spirit companion gain +1 Fort,Ref, Will'),
('Protector`s Commitment','DP','Paladin, Cha 15','Gain +1 on attacks when you or target is adjacent to bloodied ally'),
('Protector`s Shield','PrP','Shaman, Protecting Spirit','Deal 1d8 extra damage with spirit`s shield'),
('Psionic Celerity','PsP','Psionic Augmentation','+1 to speed when charging or running; augment to increase to +2'),
('Psionic Fortune','PsP','Psionic Augmentation','+1 to saving throws; augment to increase to +3'),
('Psionic Initiative','PsP','Psionic Augmentation','+3 to initiative check; augment to increase to +6'),
('Psionic Reflex','PsP','Psionic Augmentation','+1 to opportunity attacks; augment to increase to +2'),
('Psionic Scorn','DSCG','Warlock, Sorcerer-king pact, 1 or more power points','Regain 1 power point instead of regaining fell might'),
('Psionic Skill','PsP','Psionic Augmentation','+2 to checks with chosen skill; augment to increase to +3'),
('Psionic Toughness','PsP','Psionic Augmentation','+3 to hit points; augment to regain additional hit points with second wind'),
('Psychic Focus','PHB3','Shardmind','+2 damage with Psychic powers (+3/+4 at Paragon and Epic)'),
('Psychic Retaliation','DP','Kalashtar, Avenger, Oath of enmity','Use Bastion of mental clarity to change your Oath of enmity target'),
('Punishing Spike','PHB3','Battlemind, Mind spike','Mind spike imposes -2 penalty to target`s next saving throw'),
('Pursuing Step','PHB3','Battlemind, Blurred step','Triggering enemy grants combat advantage to you if adjacent'),
('Quick Draw','PHB','Dex 13','Draw a weapon with attack action, +2 to initiative'),
('Quick Reactions','PsP','Battlemind, Speed of Thought','Char for Dex on initiative check, +2 to speed withspeed of thought'),
('Quick Stow','PrP','Druid, Wild shape','Items change with you in beast form'),
('Radiant Power','PHB2','Deva','+2 damage with implement power for -2 to attack'),
('Raging Bloodcut','PrP','Barbarian','Reduce rage power damage to deal ongoing damage.'),
('Raging Storm','PHB','Con 13, Dex 13','+1 damage with lightning or thunder power'),
('Rapid Assault','PHB3','-','+2 or more damage on your first attack during an encounter'),
('Rash Sneak Attack','MP','Human, Rogue, Sneak Attack','Grant combat advantage for extra Sneak Attackdamage'),
('Rattling Wrath','MP','Charisma 15, tiefling , Rogue','Combine rattling power with infernal wrath to increase rattling penalty to -4'),
('Raven Queen’s Blessing','PHB','Channel Divinity, must worship the Raven Queen','Use Channel Divinity to invoke Raven Queen`s Blessing'),
('Razorclaw Mark','MP2','Razorclaw Shifter, Fighter','Marked creatures take -3 penalty while you`re shifting'),
('Razorclaw Spirit Shifter','PrP','Razorclaw Shifter, Any Primalclass','Shift 1 when damaged by attack against AC or Refwhile using Razorclaw Shifting'),
('Reaping Blade','MP','Dex 15, Fighter','Shift as a minor action when you drop an enemy'),
('Reckless Charge','PrP','Any Primal class','-2 AC for +1 to attack when charging'),
('Reckless Curse','AP','Human, Warlock, Warlock`s Curse','+1 to attack against cursed enemies, cursed enemies gain +1 to hit you.'),
('Reckless Scramble','MP','Rogue, Artful Dodger','Move farther instead of shifting'),
('Redoubled Efforts','MP2','Any martial class','Gain +2 attack instead of bonus to defenses aftersecond wind'),
('Refracting Mantle','PsP','Shardmind, Ardent, Shard swarm, Ardent Mantle','Allies in Ardent Mantle gain combat advantage withShard swarm'),
('Rejuvenating Spirit','PrP','Shaman, Healing spirit','Target of Healing spirit makes a saving throw.'),
('Religious Dabbler','DP','Half-Elf, Any Divine class','Use at-will power from another divine class as an encounter power'),
('Remembered Wizardry','AP','Wis 13, Deva, Wizard','Add additional daily and utility powers to spellbook'),
('Resilience of Stone','MP2','Dwarf, any martial class','Use second wind as immediate interrupt when damaged'),
('Resilient Demand','PsP','Battlemind, Battlemind`s Resilience, Battlemind`s demand','Gain +2 to all defenses with augmentedBattlemind`s demand'),
('Resilient Focus','Essentials','-','+2 to saving throws'),
('Resilient Spirit','PrP','Shaman','+2 to defences for spirit companion'),
('Resonating Covenant','PHB2','Invoker, Divine Covenant','+1 attack with at-will after using encounter or daily power'),
('Restful Healing','PHB2','-','Maximize healing between encounters'),
('Revitalizing Font of Life','PHB2','Warden, Font of Life','Successful Font of Life saving throw grants +2 bonus to other saving throws'),
('Rising Chaos','HotEC','Born of the Elements','+2 to damage rolls after taking elemental damage'),
('Rising Fury','PHB2','Barbarian','+2 damage when you reduce enemy to 0 hp'),
('Rising Spellfury','AP','Sorcerer','+1 to attack after hitting single enemy with at-will power'),
('Risky Aegis','AP','Human, Swordmage, Swordmage Aegis','+2 to attacks and damage against target affected by aegis'),
('Risky Shift','MP2','Rogue','Shift 1 extra square and grant combat advantage'),
('Rites of Spirits` Blood','PrP','Tiefling, Any Primal class','+2 to attack roll with bloodhunt and Infernal wrath'),
('Ritual Caster','PHB','Trained in Arcana or Religion','Master and perform rituals'),
('Rod Expertise','Essentials','-','+1 to attack rolls with a rod, +1 to AC and Reflexwhen holding a rod'),
('Rousing Voice','AP','Human, Bard','Ally who uses second wind gains temporary hit points'),
('Rumbling Earthshock','MP2','Genasi, earthshock , anymartial class','Deal extra damage with earthshock'),
('Rune of Eloquence','PHB3','Runepriest','Bonus to Bluff and Diplomacy equal to your number of rune feats.'),
('Rune of Hope','PHB3','Runepriest, Rune of mending','Rune of mending target also gains temporary hp'),
('Rune of Vengeance','PHB3','Runepriest','Bonus to damage equal to your number of rune feats after you are first bloodied'),
('Rune of Zeal','PHB3','Runepriest','Bonus to Athletics and Endurance equal to your number of rune feats'),
('Rune-Scribed Soul','AP','Dwarf, Any arcane class','+1 to attacks, bonus to damage after using second wind'),
('Ruthless Injury','MP','Rogue, Ruthless Ruffian,Sneak Attack','Enemy takes -2 to saving throws against conditionsdelivered with club or mace'),
('Savage Assault','PHB2','Half-orc','Target of furious assault takes -1 to defenses'),
('Savage Wolf','MP2','Ranger, Beast Mastery (Wolf)','While independant, beast knocks creatures prone'),
('Saving Inspiration','MP','Warlord','Ally gains saving throw with inspiring word'),
('Scornful Denial','DSCG','Warlock, Sorcerer-king pact','Saving throw when you regain your fell might'),
('Scouring Wrath','PHB2','Invoker, Covenant of Wrath','Armor of wrath gives target vulnerable 2'),
('Second Shot','MP2','Ranger, Hunter`s Quarry','Designate second-nearest enemy as quarry'),
('Secret of Reawakening','PHB3','Wilden, Nature`s Aspect','Change aspect and regain racial power after you drop to 0 hp'),
('Secure Encampment','MP','Wis 13,Ranger, trained inNature, Perception and Stealth','Allies gain bonus to perception and stealth during extended rest'),
('Sehanine’s Reversal','PHB','Channel Divinity, must worshipSehanine','Use Channel Divinity to invoke Sehanine’s Reversal'),
('Shadow Blood','HoS','Born of Shadow','Regain additional hp with second wind in dim light or darkness'),
('Shadow Control','HoS','Born of Shadow','+1 to defenses in dim light or darkness'),
('Shadow Mantle','HoS','Born of Shadow','Critical hits and dropping enemies grant concealment'),
('Shadow Overflow','HoS','Born of Shadow','Deal necrotic damage when you drop enemies with basic attacks'),
('Shadow Skulk','PHB2','Gnome','Stay hidden when you miss with area or ranged attack'),
('Shadow Strider','HoS','Born of Shadow','Ignore difficult terrain in dim light or darkness'),
('Shard Link','PsP','Shardmind, Telepathy, anypsionic class','Share combat advantage with ally'),
('Shared Healing Spirit','PHB2','Shaman, healing spirit','Change recipient of additional hit points'),
('Shared Memories','MP2','Deva, Warlord','Use Memory of a thousand lifetimes on adjacent ally`s roll'),
('Shared Perseverance','DP','Human, Cleric','When you grant a saving throw, your ally gains +1 to the roll'),
('Shield Defense','MP','Wis 13, Fighter','+1 AC and Reflex when power requiring a shield hits'),
('Shield Finesse','Essentials','-','Ignore check penalty for wearing a shield'),
('Shield Proficiency (Heavy)','PHB,Essentials','Str 15, Shield Proficiency (Light)','Proficiency with heavy shields'),
('Shield Proficiency (Light)','PHB,Essentials','Str 13','Proficiency with light shields'),
('Shield Push','PHB','Fighter, Combat Challenge','Push 1 square to target hit by Combat Challengeattack'),
('Shielding Familiar','AP','Arcane Familiar, 6th-level or higher utility power','Trade utility power for shielding familiar power'),
('Shifting Defense','PHB3','-','Shift 1 square when you use total defense'),
('Shifting Stone','PsP','Dwarf, Monk','Shift with save to avoid being knocked prone'),
('Sideways Defense','MP','Human, Fighter, Combat Challenge','Adjacent allies gain +1 defense against marked enemy'),
('Skald Training','HotFW','Bard, Majestic Word','Exchange majestic word for skald`s aura'),
('Skill Focus','PHB,Essentials','Training in chosen skill','+3 to checks with chosen skill'),
('Skill Power','PHB3','2nd Level','Gain Skill Power of your level or lower'),
('Skill Training','PHB,Essentials','-','Gain training in one skill'),
('Skins of the Slain','PrP','Any Primal class, proficiency with Hide armor','Gain bonus to Intimidate checks equal to hide armour`s enchantment bonus'),
('Skipping Stone Flurry','PsP','Monk, Flurry of Blows','Target one enemy within 10 squares with Flurry of Blows and sling'),
('Skittering Mouse Style','PsP','Small, Monk','Shift through enemies` spaces with movement technique'),
('Slaying Action','MP','Rogue, Sneak Attack','Deal Sneak Attack damage again with an action point'),
('Sling Expertise','Essentials','-','+1 to attack rolls with a sling , don`t provokeopportunity attacks when making ranged attacks with a sling'),
('Snapping Lizard','MP2','Ranger, Beast Mastery (lizard)','While independant, beast damages creature that moves away'),
('Sneaky Accuracy','MP','Elf , Rogue, Sneak Attack','Retain elven accuracy on an enemy’s miss'),
('Sorcerous Assassin','AP','Drow, Sorcerer','+2 to damage with poison or psychic powers, +1Stealth'),
('Sorcerous Blade Channeling','PHB2','Sorcerer','Use dagger to make ranged attacks as melee attacks'),
('Soulstealer of Moil','HoS','Any Shadow Summoningpower','Gain temporary hp when you use shadow summoning'),
('Spear Expertise','Essentials','-','+1 to attack rolls with a spear , +1 damage whencharging with a spear'),
('Spectral Step','HoS','Any Shadow power','Become insubstantial with action point'),
('Speed Loader','PHB2','-','Load crossbow as  free action instead of minor'),
('Speed of Sea and Sky','MP2','Genasi, Warlord, Swiftcurrentor Windwalker','Elemental manifestation power grants allies speed bonus'),
('Speedy Response','MP','Dex 15, Rogue','Gain speed when hit by an opportunity attack'),
('Spellseer Familiar','AP','Arcane Familiar, 6th-level or higher utility','Trade utility power for spellseer familiar power'),
('Spider`s Swiftness','PrP','Drow, Any Primal class','+1 to speed, or +2 when affected by polymorph or rage power'),
('Spirit of Vigor','DSCG','Shaman, Elemental spirit','Ally gains temporary hp when you conjure your spirit companion'),
('Spirit Speaker','PHB2','Shaman, Speak with Spirits','Speak with spirits grants skill bonus to ally'),
('Spirit Tribe','PrP','Shaman, Speak with spirits','Allies gain +2 to checks with Speak with spiritschosen skill'),
('Spirit`s Fey step','PrP','Eladrin, Shaman','Teleport your spirit companion when you use Fey step'),
('Spirit`s Step','DSCG','Shaman, Elemental spirit','Ally adjacent to dismissed spirit can shift'),
('Spirits of Stealth','PrP','Gnome, Any Primal class','+3 damage against bloodied creatures while you`re hidden'),
('Spirits of Stone','PrP','Dwarf, Any Primal class','+2 to next attack roll when you use second wind'),
('Spirits of the Primal Dragons','PrP','Dragonborn, Any Primal class','Deal 1d8 extra damage of the same type asDragon breath after becoming bloodied'),
('Spiritbond Defense','PHB3','Seeker, Spiritbond','Use second wind and grant bonus to defense to adjacent ally'),
('Spring Step','PHB3','-','Shift 1 square when you stand up'),
('Springing Charge','PHB3','Minotaur','Make second charge attack after critical on first charge attack'),
('Staff Expertise','Essentials','-','+1 to attack rolls and reach with a staff , don`t provoke opportunity attacks when using a staff as an implement'),
('Stagger Smash','PrP','Any Primal class','Push target 1 when you daze or stun it with a primal power'),
('Stalker Spirit Adept','PHB2','Shaman, Stalker Spirit','Allies adjacent to spirit companion can shift as free action'),
('Startling Distraction','MP2','Ghost sound, rogue','After using ghost sound, roll twice on Stealthchecks'),
('Steady Feet','PHB3','-','Ignore 1 square of Difficult terrain when you walk'),
('Stinging Swarm','PrP','Druid, Primal Swarm, Wild shape','While you`re in beast form, enemies that damage you grant combat advantage to you'),
('Stone Step Spirits','PrP','Dwarf, Any Primal class','Ignore 1 square of difficult terrain when you move, or all difficult terrain when'),
('Stoneroot`s Endurance','Essentials','-','When subjected to critical hit , roll a d20, attack is a normal hit if roll is a 10 or higher'),
('Stormhawk`s Vengence','Essentials','-','An enemy that reduces you to 0 hit points takes 10thunder damage'),
('Stormheart Push','PrP','Warden, Stormheart','Push target 2 with Stormheart instead of sliding it'),
('Streak of Light','HotFW','Pixie','Gain combat advantage against enemies you charge'),
('Street Thug','MP','Strength 13, Constitution 13,Rogue','Treat mace as light blade'),
('Strength of Stone','DP','Goliath, Paladin','Ally gains resist all when you use Lay on hands orcall of virtue'),
('Strength of Valor','PHB2','Bard, Virtue of Valor','Virtue of Valor also grants +2 damage'),
('Strengthened Bond','PHB3','Seeker, Seeker`s Bond','Regain Seel<er`s Bond power when first bloodied'),
('Strengthening Spirit','PrP','Shaman, Healing spirit','Allies adjacent to companion gain Wis temporary hp when you use healing spirit'),
('Strike and Shove','PHB3','-','Push target after critical hit with Melee attack'),
('Strong-Willed Summoning','PrP','Druid','Creatures you summon gain +1 to attack with instinctive actions'),
('Student of the Cosmos','AP','Sorcerer, Cosmic Magic','Gain additional benefit based on your current phase'),
('Sudden Call','PrP','Shaman','Use call spirit companion as a free action once per encounter'),
('Sudden Roots','PHB2','Warden','Enemy hit by opportunity attack is slowed'),
('Superior Implement Training','PHB3','-','Use one superior implement of a type open to your class'),
('Superior Fortitude','Essentials','Str 15 or Con 15','+2 Fortitude , resist 3 ongoing damage'),
('Superior Reflexes','Essentials','Dex 15 or Int 15','+2 Reflex , combat advantage during first turn of an encounter'),
('Superior Will','Essentials','Wis 15 or Cha 15','+2 Will , make saving throws at start of your turn against dazed and stunned'),
('Sure Climber','PHB','Trained in Athletics','Climb at normal speed on any surface, +1 toAthletics'),
('Surging Flame','PHB2','-','Fire-resistant target takes extra damage from firepowers'),
('Surging Mantle','PsP','Ardent, Ardent Mantle','Increase Ardent Mantle radius by 2 while you have 0 power points'),
('Surprise Knockdown','PHB','Str 15, rogue','Knock target prone with critical hit'),
('Surprising Charge','MP','Dexterity 17, Fighter or Rogue','+1[W] damage when charging with light blade orspear'),
('Swift Footwork','MP2','Ranger, Rogue','Increase your shifts from encounter and daily powers by 2'),
('Swift Jaguar','PrP','-','+2 to Perception checks; increase by 1 for each ally with feat'),
('Swift Recovery','Essentials','Training in Endurance','+3 to healing surge value'),
('Swift Slayer','PrP','Barbarian, Whirling Slayer','Shift your dex modifier with Whirling Slayer'),
('Tactical Assault','PHB','Warlord, Tactical Presence','Ally gains bonus to damage equal to your Intmodifier'),
('Tactical Inspiration','MP','Eladrin, Warlord','Add Int modifier to inspiring word hp restored'),
('Tainted Wounds','HoS','-','Your melee attacks prevent enemies from gaining hp'),
('Take Measure','MP','Wis 15, Fighter','+2 to all defenses against target with melee critical hit'),
('Targeted Assault','PrP','Barbarian','+2 to attacks against creatures marking you'),
('Taunting Visage','DP','Changeling or Doppelganger,Avenger, Oath of enmity','Use change shape to gain combat advantage against your Oath of enmity target'),
('Teamwork Defense','PHB3','-','+1 AC when adjacent to ally who also has this feat'),
('Teeny Target','HotFW','Pixie','Gain partial cover when in an ally`s space'),
('Telekinetic Savant','DSCG','Battlemind, Wild focus','Increase the forced movement of your battlemind powers by 1'),
('Telepathic Mark','MP2','Kalashtar, Fighter','On a crit, mark enemies within range of telepathy'),
('Tempest Magic','AP','Sorcerer, Con 13, Dex 13,Storm Magic','Extra damage with lightning or thunder powers'),
('Tenacious Resolve','Essentials','Training in Endurance','+5 to saving throws against ongoing damage'),
('Terrain Advantage','Essentials','-','Combat advantage against targets in a square ofdifficult terrain'),
('Thirst for Battle','PHB2','Half-orc','+3 to Initiative and one additional healing surge'),
('Thought Warning','PsP','Kalashtar, Battlemind,Telepathy','You and allies shift when you drop to 0 power points'),
('Thunder Hammer','MP','Con 15, Fighter','Enemy takes -2 to saving throws against conditions delivered with hammer or mace'),
('Thunderborn Rage','PrP','Barbarian, Thunderborn Wrath','+5 to thunder damage of Thunderborn Wrath'),
('Thundertusk Companion','MP','Dwarf, Ranger, Beast Mastery','Your boar`s Hp increases by your level'),
('Timely Respite','PHB2','-','Second wind or total defense grants saving throw'),
('Tome Expertise','HotEC','-','+1 to attack rolls with tomes, enemies adjacent to your conjurations or summoned creatures grant combat advantage'),
('Totem Expertise','HotFW','-','+1 to attack rolls with totems, ignore partial cover and partial concealment on those attacks'),
('Toughness','PHB,Essentials','-','Gain 5 additional hit points per tier'),
('Trap Sense','MP','Wisdom 13, Rogue','+2 to all defenses against traps, +2 to find traps'),
('Treetop Sniper','MP2','Elf, rogue','Use bow with Sneak Attack and rogue exploits'),
('Trickster`s Mark','MP2','Gnome, Fighter','Use Ghost sound to mark enemy'),
('Triggered Chaos','AP','Halfling, Sorcerer, Wild Mage','Shift or slide an enemy after using second chance'),
('True Dragon`s Soul','AP','Dragonborn, Sorcerer, Dragon Magic','+1 to defenses after being bloodied, breath weapon ignores resistance'),
('Tunnel Stalker','MP','Strength 13, Constitution 13,Dwarf , Rogue','Treat one-handed axes , hammers , and picks aslight blades'),
('Twilight Training','MP2','Human, Ranger','Gain low-light vision'),
('Twist the Arcane Fabric','AP','Eladrin, Any arcane class','Fey step an ally out of your power`s area of effect'),
('Two-Fisted Shooter','MP','Rogue','Treat hand crossbow as off-hand weapon , reloadfree action'),
('Two-Handed Weapon Expertise','HotFW','-','+1 to attack rolls with two-handed melee weapons, +1 to damage rolls of charge attacks with two-handed melee weapons'),
('Two-Weapon Defense','PHB,Essentials','Dex 13, Two-Weapon Fighting','+1 to AC and Reflex while holding a weapon in each hand'),
('Two-Weapon Fighting','PHB,Essentials','Dex 13','+1 damage while holding a melee weapon in each hand'),
('Two-Weapon Threat','PHB2','Dex 13, Two-Weapon Fighting','+3 damage on opportunity attacks with two melee weapons'),
('Ubiquitous Step','PsP','Eladrin, Fey step, Psionic Augmentation','Regain Fey step at 0 power points'),
('Unarmored Agility','PHB3','-','+2 to AC while wearing cloth armor or no armor'),
('Unbalancing Wrath','MP','Tiefling, Warlord','Infernal wrath target grants combat advantage'),
('Unfailing Vigor','PHB3','-','Spend a healing surge If you roll 18-20 on death saving throw'),
('Unleash the Beast','DP','Shifter, Avenger, Oath of enmity','Use racial power as immediate reaction when hit by your Oath of enmity target'),
('Unseen Dread','PsP','Gnome, Psion','Slide target you are hidden from after hitting with attack'),
('Vengeful Beast','MP','Ranger, Beast Mastery,Hunter`s Quarry','Beast gains +1 to attack and damage rolls against quarry'),
('Vengeful Curse','AP','Tiefling, Warlock, Warlock`s Curse','Curse enemy that hits you as an immediate reaction'),
('Venomous Spider','MP2','Ranger, Beast Mastery (spider)','While independant, beast slows creatures and gives -2 attack'),
('Versatile Channeler','DP','Any Divine class, Channel Divinity','Gain another class`s Channel Divinity power'),
('Versatile Expertise','PHB3','-','Bonus to attacks with weapons and implements of your choice'),
('Versatile Talent','MP2','Human, Fighter, Fighter Weapon Talent','Gain Fighter Weapon Talent with both weapon types'),
('Vestige Adept','AP','Warlock, Vestige Pact','Change your vestige after pact boon is triggered'),
('Victor`s Confidence','MP','Con 15, Fighter','+2 to saving throws after reducing an enemy to 0 hp'),
('Vicious Advantage','PHB3','-','Gain combat advantage against slowed or immobilized targets'),
('Vicious Darkfire','DP','Drow, Avenger, Oath of enmity','Use darkfire against your Oath of enmity target to give it vulnerability to all damage'),
('Vicious Intrusion','PsP','Psion, Distract','Extra damage to target of distract'),
('Vigorous Spirit','PrP','Shaman, Healing spirit','Target of healing spirit regains Wis additional hp'),
('Vine`s Arms','HotFW','Wilden, Nature`s Aspect','+2 to Acrobatics checks, increase reach withNature`s Aspect'),
('Violent Awakening','PsP','Half-orc, Monk, Furious assault, Flurry of Blows','Flurry of Blows deals extra damage with Furious assault'),
('Virtuous Recovery','DP','Paladin','Gain resist all when you spend a healing surge'),
('Walk among Men','HotFW','Satyr','Appear as an Eladrin, Elf or Human'),
('Wand Expertise','Essentials','-','+1 to attack rolls using a wand , ignore partial and superior cover when using a wand'),
('Warding Defense','PHB3','-','Allies benefit when you use total defense and wield a shield'),
('Warding Shard Swarm','PHB3','Shardmind, Shard swarm','+2 defenses when you use shard swarm'),
('Warding Soul','AP','Half-elf, Sorcerer','Adjacent allies gain your resistances'),
('Warforged Example','DP','Warforged, Paladin','Allies can save against ongoing damage when you use Warforged resolve'),
('Warforged Faith','DP','Warforged, Any Divine class','Warforged resolve also affects adjacent ally'),
('Warforged Superiority','MP2','Warforged, Fighter, Combat Superiority','Knock creature prone when using Combat Superiority'),
('Warpath Leader','MP2','Half-Orc, Warlord, Combat Leader','Allies within 5 squares gain +2 speed when charging'),
('Wasteland Wanderer','Essentials','-','+2 to Nature , Perception , and initiative'),
('Water Splitting Stone','PsP','Monk','Unarmed strike critical hit causes target to lose resistances'),
('Watcher Spirit Adept','PrP','Shaman, Watcher spirit','Allies adjacent to companion gain +2 to Insight andPerception'),
('Watchful Guardian','PrP','Druid, Primal Guardian, Wild shape','While in beast form, you and allies adjacent to you gain +2 to opportunity attack rolls'),
('Watchful Owl','PrP','-','+2 to Perception checks; increase by 1 for each ally with feat'),
('Watchful Redoubt','PHB3','-','+1 attack when you use total defense'),
('Weapon Expertise','PHB2','-','+1 to attacks with weapon group'),
('Weapon Focus','PHB,Essentials','-','+1 damage with chosen weapon group'),
('Weapon Proficiency','PHB,Essentials','-','Gain proficiency with the weapon of your choice'),
('Wielder of Piercing Flame','MP','Genasi, rogue','Firepulse ignores target’s resistance or immunitywhen you have combat advantage'),
('Wild Bull Rush','PrP','Druid, Wild shape','While in beast form, +2 to bull rush attacks and use bull rush against any size target'),
('Wild Sage','PrP','Trained in Nature','+5 to Nature knowledge and monster knowledge checks to identify natural creatures, and gain a ritual'),
('Wild Senses','PHB2','Shifter','Roll twice when following tracks, +3 to Initiative'),
('Wildblood Cunning','PHB2','Warden, Wildblood','Shift when you use second wind'),
('Wildblood Fury','PrP','Warden, Wildblood','Gain bonus to damage rolls against enemies you`ve marked when you use second wind'),
('Wilderness Skirmisher','Essentials','-','Partial cover when in a square of difficult terrain , +2 to Acrobatics and Athletics'),
('Wind of Sympathy','PsP','Ardent, Ardent Mantle','Use your second wind and ally in ardent mantle can use second wind'),
('Winter Walker','HoS','-','Ice walk and +5 to ice related skill checks'),
('Wintertouched','PHB','-','Gain combat advantage against foe vulnerable to cold'),
('World Serpent`s Grasp','Essentials','-','When hitting a slowed or immobilized target, it is knocked prone'),
('World Speaker Spirit Adept','PrP','Shaman, World Speaker Spirit','You and allies ignore difficult terrain while adjacent to spirit companion'),
('Wrath of Ages Past','DP','Dwarf, Invoker, Covenant of Wrath','Gain more damage when you use Armour of wrathagainst enemies larger than you'),
('Wrath of the Mountain King','DP','Goliath, Invoker, Covenant of Wrath','Knock Target prone when you use Armour of wrath'),
('Wrathful Magic','AP','Tiefling, Any arcane class','Use infernal wrath against missed target'),
('Wrenching Grasp','MP2','Fighter, Brawler Style','Deal Dex modifier damage with failed grab'),
('Zerth Instincts','PsP','Githzerai, Iron mind, anypsionic class','Shift with Iron mind, or expend Iron mind to cancel surprise'),
('Zuwoth`s Enlightened Step','PHB3','Githzerai','You don`t provoke from enemies that have not yet acted')