INSERT INTO feats (`type`, `name`, `source`, `prerequisites`, `Benefit`) VALUES
('Paragon','Action Recovery','PHB','Human','Gain extra saving throws by spending an action point'),
('Paragon','Agile Athlete','PHB','-','Roll twice with Acrobatics and Athletics checks'),
('Paragon','Arcane Reach','PHB','Dex 15','Choose square within 2 as origin with close attack power'),
('Paragon','Armor Specialization (Chainmail)','PHB','Dex 15, training with chainmail','+1 to AC with chainmail, reduce check penalty by 1'),
('Paragon','Armor Specialization (Hide)','PHB','Con 15, training with hide armor','+1 to AC with hide armor, reduce check penalty by 1'),
('Paragon','Armor Specialization (Plate)','PHB','Con 15, training with plate armor','+1 to AC with plate armor'),
('Paragon','Armor Specialization (Scale)','PHB','Dex 15, training with scale armor','+1 to AC with scale armor, ignore speed penalty'),
('Paragon','Avalanche Reaver','MP2','Goliath, any martial class','Push target of charge 1 square, shift into vacated square'),
('Paragon','Avandra`s Gift','MP','Halfling , rogue','Gain combat advantage with second chance'),
('Paragon','Back to the Wall','PHB','-','+1 to melee attack, damage, AC when adjacent to a wall'),
('Paragon','Bleeding Backstab','MP','Rogue, Sneak Attack','Deal ongoing 5 damage with daily rogue power'),
('Paragon','Blood Thirst','PHB','-','+2 to damage against bloodied foes'),
('Paragon','Bloody Tenacity','MP','Human , any martial class','+2 to all defenses when first bloodied'),
('Paragon','Brutal Bludgeon','MP2','Rogue','Clubs and maces gain brutal 1 property'),
('Paragon','Combat Anticipation','PHB','-','+1 to defenses against ranged, area, close attacks'),
('Paragon','Combat Commander','PHB','Warlord, Combat Leader','Bonus to Combat Leader equals Cha or Int modifier'),
('Paragon','Combat Opportunist','MP2','Rogue','Ally`s opportunity attack grants combat advantageto you'),
('Paragon','Cull the Weak','MP','Charisma 15, rogue','Deal +2 damage in melee to bloodied or weakenedenemies'),
('Paragon','Danger Sense','PHB','-','Roll twice for initiative, use the higher result'),
('Paragon','Darkjumper','MP','Drow , rogue','Teleport as free action within your cloud of darkness'),
('Paragon','Deadly Axe','PHB','Str 17, Con 13','Treat all axes as high crit weapons'),
('Paragon','Deceptive Staff','MP2','Any martial class','Gain combat advantage after you miss with a staff'),
('Paragon','Defensive Advantage','PHB','Dex 17','+2 AC when you have combat advantage against enemy'),
('Paragon','Deft Blade','MP2','Any martial class','Basic attack with light blade targets AC or Reflex'),
('Paragon','Devastating Critical','PHB','-','Deal additional 1d10 damage on a critical hit'),
('Paragon','Disheartening Ambush','MP2','Rogue, Sneak Attack','Forgo one Sneak Attack die to give your attack therattling keyword'),
('Paragon','Distant Shot','PHB','-','Ignore −2 penalty for long range'),
('Paragon','Dragon Breath Scoundrel','MP2','Rogue, dragonborn, Sneak Attack','Sneak Attack creatures hit with dragon breath'),
('Paragon','Dwarven Durability','PHB','Dwarf','Increase number of healing surges, healing surge value'),
('Paragon','Dwarven Recovery','MP2','Dwarf, any martial class','+5 to saving throws after second wind'),
('Paragon','Elusive Movement','MP2','Rogue','+1 AC and Reflex if you moved at least 3 squares'),
('Paragon','Empowered Dragon Breath','PHB','Dragonborn, dragon breathracial power','Dragon breath uses d10s'),
('Paragon','Evasion','PHB','Dex 15','No damage from missed area or close attack'),
('Paragon','Evasive Footwork','MP','Dexterity 17, Charisma 15,rogue','+1 to AC and Reflex when you shift 2 or more squares'),
('Paragon','Expert Sneak','MP2','Rogue','Gain combat advantage against enemies with some conditions'),
('Paragon','Fey Gambit','MP','Eladrin, rogue','Gain combat advantage against enemy you fey step next to'),
('Paragon','Feywild Protection','PHB','Eladrin, Fey step racial power','+2 to defenses when you use fey step'),
('Paragon','Fiery Rebuke','PHB','Tiefling, infernal wrath racial power','Cause fire damage with infernal wrath'),
('Paragon','Fleet-Footed','PHB','-','+1 to speed'),
('Paragon','Great Fortitude','PHB','-','+2 to Fortitude defense'),
('Paragon','Group Flanking','MP','Half-elf, rogue','Allies gain combat advantage against enemy you flank'),
('Paragon','Hammer Rhythm','PHB','Str 15, Con 17','Damage with hammer or mace on a miss'),
('Paragon','Hammer Shock','MP2','Intimidate trained, any martial class','Melee basic attack with hammer gains rattling keyword'),
('Paragon','Heavy Blade Opportunity','PHB','Str 15, Dex 15','Use at-will power with opportunity attack'),
('Paragon','Icy Heart','HotEC','-','+3 feat bonus to cold damage rolls; +4 at 21st level;slow nearby enemies when character takes cold damage'),
('Paragon','Impaling Spear','MP2','Any martial class','Melee basic attack with spear targets Reflex'),
('Paragon','Improved Second Wind','PHB','-','Heal 5 additional damage with second wind'),
('Paragon','Inescapable Force','PHB','-','Force powers ignore insubstantial, deal additional damage'),
('Paragon','Infernal Sneak Attack','MP','Tiefling, rogue, Sneak Attack','Combine Sneak Attack with infernal wrath for extra damage'),
('Paragon','Iron Will','PHB','-','+2 to Will defense'),
('Paragon','Lashing Flail','MP2','Any martial class','Melee basic attack with flail slides creature'),
('Paragon','Lasting Frost','PHB','-','Target hit with cold power gains vulnerable cold 5'),
('Paragon','Light Blade Precision','PHB','Dex 13, Small or Medium size','+2 damage against Large or larger targets'),
('Paragon','Lightning Arc','PHB','-','Affect second target with lightning power on critical hit'),
('Paragon','Lightning Reflexes','PHB','-','+2 to Reflex defense'),
('Paragon','Martial Accuracy','MP2','Elf, any martial class','Roll twice when using elven accuracy on exploit'),
('Paragon','Mettle','PHB','-','No damage from missed area or close attacks'),
('Paragon','Opportunistic Sneak Attack','MP','rogue, Sneak Attack','Sneak Attack with opportunity attack slows target'),
('Paragon','Piercing Pick','MP2','Any martial class','Melee basic attack with pick targets AC or Fortitude'),
('Paragon','Point-Blank Shot','PHB','-','Ignore cover and concealment within 5 squares'),
('Paragon','Polearm Gamble','PHB','Str 15, Wis 15','Make opportunity attack against adjacent enemy'),
('Paragon','Primal Eye','PHB3','Seeker','Add Str or Dex modifier to ranged basic attackdamage rolls'),
('Paragon','Prime Slayer','MP','Elf, rogue','+2 to ranged damage rolls if no ally is closer to the target'),
('Paragon','Psychic Lock','PHB','-','Target hit with psychic power takes −2 on nextattack roll'),
('Paragon','Punishing Axe','MP2','Any martial class','Treat rolls of 1 or 2 on critical hit and high crit dice as 3s'),
('Paragon','Rapid Practice','MP2','Practiced Study feat, any martial class','Perform martial practices in half the time'),
('Paragon','Resounding Thunder','PHB','-','Add 1 to size of blast or burst with thunder keyword'),
('Paragon','Rogue Weapon Mastery','MP','Elf, rogue','Treat daggers and shuriken as high crit weapons'),
('Paragon','Roundabout Charge','MP','rogue, Acrobatics trained','End your charge in any square adjacent to target'),
('Paragon','Running Shot','PHB','Elf','No attack penalty to ranged attacks after you run'),
('Paragon','Scimitar Dance','PHB','Str 15, Dex 17','Deal Dex modifier damage on miss'),
('Paragon','Second Implement','PHB','Wizard, Arcane Implement Mastery class feature','Gain mastery with second arcane implement'),
('Paragon','Secret Stride','PHB','Trained in Stealth','No penalty to Stealth with move while hiding orsneaking'),
('Paragon','Seize the Moment','PHB','Dex 17','Gain combat advantage over foe with lowerinitiative'),
('Paragon','Shield Specialization','PHB','Dex 15, Shield Proficiency (Heavy or Light)','+1 to AC and Reflex when using a shield'),
('Paragon','Sly Hunter','PHB','Wis 15','+3 damage with bow against isolated target'),
('Paragon','Sneaky Gnome','MP2','Rogue, gnome, Sneak Attack','Sneak Attack while invisible does not end invisibility'),
('Paragon','Sneaky Opportunity','MP2','Rogue','Deal extra damage with light blade on opportunity attack'),
('Paragon','Solid Sound','PHB','Con 13','+2 to defense after you use thunder or force power'),
('Paragon','Spear Push','PHB','Str 15, Dex 13','Add 1 square to distance pushed with spear orpolearm'),
('Paragon','Spell Focus','PHB','Cha 13, wizard','−2 to saves against your wizard spells'),
('Paragon','Steady Shooter','PHB','Con 15','+3 damage with crossbow if you don’t move'),
('Paragon','Sweeping Flail','PHB','Str 15, Dex 15','+2 to attacks with flail against foe with a shield'),
('Paragon','Twofold Curse','PHB','Warlock, Warlock’s Curse','Curse the two nearest enemies'),
('Paragon','Uncanny Dodge','PHB','Wis 15','Enemies denied bonus to attack from combat advantage'),
('Paragon','Underfoot','PHB','Halfling, trained in Acrobatics','Move through spaces of Large or larger creatures'),
('Paragon','Unerring Ambush','MP2','Rogue, First Strike','In first round, roll two attack rolls against enemy that has not yet acted'),
('Paragon','Wicked Blade','MP2','Any martial class','Basic attack with heavy blade gains high crit property')